using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharpGL.Enumerations
{
    public enum DebugSource : uint
    {
        API_ARB = GL.GL_DEBUG_SOURCE_API_ARB,
        WINDOW_SYSTEM_ARB = GL.GL_DEBUG_SOURCE_WINDOW_SYSTEM_ARB,
        SHADER_COMPILER_ARB = GL.GL_DEBUG_SOURCE_SHADER_COMPILER_ARB,
        THIRD_PARTY_ARB = GL.GL_DEBUG_SOURCE_THIRD_PARTY_ARB,
        APPLICATION_ARB = GL.GL_DEBUG_SOURCE_APPLICATION_ARB,
        OTHER_ARB = GL.GL_DEBUG_SOURCE_OTHER_ARB,
    }

    public enum DebugType : uint
    {
        ERROR_ARB = GL.GL_DEBUG_TYPE_ERROR_ARB,
        DEPRECATED_BEHAVIOR_ARB = GL.GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR_ARB,
        UNDEFINED_BEHAVIOR_ARB = GL.GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR_ARB,
        PORTABILITY_ARB = GL.GL_DEBUG_TYPE_PORTABILITY_ARB,
        PERFORMANCE_ARB = GL.GL_DEBUG_TYPE_PERFORMANCE_ARB,
        OTHER_ARB = GL.GL_DEBUG_TYPE_OTHER_ARB,
    }

    public enum DebugSeverity : uint
    {
        HIGH_ARB = GL.GL_DEBUG_SEVERITY_HIGH_ARB,
        MEDIUM_ARB = GL.GL_DEBUG_SEVERITY_MEDIUM_ARB,
        LOW_ARB = GL.GL_DEBUG_SEVERITY_LOW_ARB,
        NOTIFICATION_ARB = GL.GL_DEBUG_SEVERITY_NOTIFICATION_ARB,
    }
}
