using System;
using System.ComponentModel;
using System.Drawing.Design;
using System.Runtime.InteropServices;

namespace CSharpGL {
    partial class GLBitmap {
        public static readonly IReadOnlyDictionary<GLuint, int> internalFormat2Bytes = new Dictionary<GLuint, int>() {
            {GL.GL_DEPTH_COMPONENT, 1 },
            {GL.GL_DEPTH_STENCIL,   2 },
            {GL.GL_RED        ,     1 },
            {GL.GL_RG         ,     2 },
            {GL.GL_RGB        ,     3 },
            {GL.GL_RGBA       ,     4 },
            //
            { GL.GL_R8, 1 },
            { GL.GL_R8_SNORM, 1 },
            { GL.GL_R16, 2 },
            { GL.GL_R16_SNORM, 2 },
            { GL.GL_RG8, 2 },
            { GL.GL_RG8_SNORM, 2 },
            { GL.GL_RG16, 4 },
            { GL.GL_RG16_SNORM, 4 },
            { GL.GL_R3_G3_B2, 1 },
            { GL.GL_RGB4, 2 },
            { GL.GL_RGB5, 2 },
            { GL.GL_RGB8, 3 },
            { GL.GL_RGB8_SNORM, 3 },
            { GL.GL_RGB10, 4 },
            { GL.GL_RGB12, 5 },
            { GL.GL_RGB16_SNORM, 6 },
            { GL.GL_RGBA2, 1 },
            { GL.GL_RGBA4, 2 },
            { GL.GL_RGB5_A1, 2 },
            { GL.GL_RGBA8, 4 },
            { GL.GL_RGBA8_SNORM, 4 },
            { GL.GL_RGB10_A2, 4 },
            { GL.GL_RGB10_A2UI, 4 },
            { GL.GL_RGBA12, 6 },
            { GL.GL_RGBA16, 8 },
            { GL.GL_SRGB8, 3 },
            { GL.GL_SRGB8_ALPHA8, 4 },
            { GL.GL_R16F, 2 },
            { GL.GL_RG16F, 4 },
            { GL.GL_RGB16F, 6 },
            { GL.GL_RGBA16F, 8 },
            { GL.GL_R32F, 4 },
            { GL.GL_RG32F, 8 },
            { GL.GL_RGB32F, 12 },
            { GL.GL_RGBA32F, 16 },
            { GL.GL_R11F_G11F_B10F, 4 },
            { GL.GL_RGB9_E5, 4 },
            { GL.GL_R8I, 1 },
            { GL.GL_R8UI, 1 },
            { GL.GL_R16I, 2 },
            { GL.GL_R16UI, 2 },
            { GL.GL_R32I, 4 },
            { GL.GL_R32UI, 4 },
            { GL.GL_RG8I, 2 },
            { GL.GL_RG8UI, 2 },
            { GL.GL_RG16I, 4 },
            { GL.GL_RG16UI, 4 },
            { GL.GL_RG32I, 8 },
            { GL.GL_RG32UI, 8 },
            { GL.GL_RGB8I, 3 },
            { GL.GL_RGB8UI, 3 },
            { GL.GL_RGB16I, 6 },
            { GL.GL_RGB16UI, 6 },
            { GL.GL_RGB32I, 12 },
            { GL.GL_RGB32UI, 12 },
            { GL.GL_RGBA8I, 4 },
            { GL.GL_RGBA8UI, 4 },
            { GL.GL_RGBA16I, 8 },
            { GL.GL_RGBA16UI, 8 },
            { GL.GL_RGBA32I, 16 },
            { GL.GL_RGBA32UI, 16 },
            //
            { GL.GL_COMPRESSED_RED, 1 },
            { GL.GL_COMPRESSED_RG, 2 },
            { GL.GL_COMPRESSED_RGB, 3 },
            { GL.GL_COMPRESSED_RGBA, 4 },
            { GL.GL_COMPRESSED_SRGB, 3 },
            { GL.GL_COMPRESSED_SRGB_ALPHA, 4 },
            { GL.GL_COMPRESSED_RED_RGTC1, 1 },
            { GL.GL_COMPRESSED_SIGNED_RED_RGTC1, 1 },
            { GL.GL_COMPRESSED_RG_RGTC2, 2 },
            { GL.GL_COMPRESSED_SIGNED_RG_RGTC2, 2 },
            { GL.GL_COMPRESSED_RGBA_BPTC_UNORM, 4 },
            { GL.GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM, 4 },
            { GL.GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT, 3 },
            { GL.GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT, 3 },
        };
    }
}