using System;
using System.ComponentModel;
using System.Drawing.Design;

namespace CSharpGL
{
    /// <summary>
    /// VAO是用来管理VBO的。可以进一步减少DrawCall。
    /// <para>VAO is used to reduce draw-call.</para>
    /// </summary>
    //[Editor(typeof(PropertyGridEditor), typeof(UITypeEditor))]
    public sealed class VertexArrayObject : IDisposable
    {
        private const string strVertexArrayObject = "Vertex Array Object";

        /// <summary>
        /// vertex attribute buffers('in vec3 position;' in shader etc.)
        /// </summary>
        [Category(strVertexArrayObject)]
        [Description("vertex attribute buffers('in vec3 position;' in shader etc.)")]
        public VertexBuffer[] VertexAttributeBuffers { get; private set; }

        /// <summary>
        /// The one and only one index buffer used to indexing vertex attribute buffers.
        /// </summary>
        [Category(strVertexArrayObject)]
        [Description("The one and only one index buffer used to indexing vertex attribute buffers.)")]
        public IndexBuffer IndexBuffer { get; private set; }

        private uint[] ids = new uint[1];

        /// <summary>
        /// 此VAO的ID，由OpenGL给出。
        /// <para>Id generated by glGenVertexArrays().</para>
        /// </summary>
        [Category(strVertexArrayObject)]
        [Description("Id generated by glGenVertexArrays().")]
        public uint Id { get { return ids[0]; } }

        /// <summary>
        /// VAO是用来管理VBO的。可以进一步减少DrawCall。
        /// <para>VAO is used to reduce draw-call.</para>
        /// </summary>
        /// <param name="indexBuffer">index buffer pointer that used to invoke draw command.</param>
        /// <param name="vertexAttributeBuffers">给出此VAO要管理的所有VBO。<para>All VBOs that are managed by this VAO.</para></param>
        public VertexArrayObject(IndexBuffer indexBuffer, params VertexBuffer[] vertexAttributeBuffers)
        {
            if (indexBuffer == null)
            {
                throw new ArgumentNullException("indexBuffer");
            }
            // Zero vertex attribute is allowed in GLSL.
            //if (vertexAttributeBuffers == null || vertexAttributeBuffers.Length == 0)
            //{
            //    throw new ArgumentNullException("vertexAttributeBuffers");
            //}

            this.IndexBuffer = indexBuffer;
            this.VertexAttributeBuffers = vertexAttributeBuffers;
        }

        /// <summary>
        ///
        /// </summary>
        public override string ToString()
        {
            return string.Format("VAO Id: {0}", this.Id);
        }

        /// <summary>
        ///
        /// </summary>
        public void Dispose()
        {
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        ///
        /// </summary>
        ~VertexArrayObject()
        {
            this.Dispose(false);
        }

        private bool disposedValue;

        private void Dispose(bool disposing)
        {
            if (this.disposedValue == false)
            {
                if (disposing)
                {
                    // Dispose managed resources.
                }

                // Dispose unmanaged resources.

                IntPtr ptr = GL.Instance.GetCurrentContext(); //Win32.wglGetCurrentContext();
                if (ptr != IntPtr.Zero)
                {
                    {
                        var fucntion = GL.Instance.GetDelegateFor("glDeleteVertexArrays", GLDelegates.typeof_void_int_uintN) as GLDelegates.void_int_uintN;
                        fucntion(1, this.ids);
                        this.ids[0] = 0;
                    }
                    {
                        VertexBuffer[] vertexAttributeBuffers = this.VertexAttributeBuffers;
                        if (vertexAttributeBuffers != null)
                        {
                            foreach (VertexBuffer item in vertexAttributeBuffers)
                            {
                                item.Dispose();
                            }
                        }
                    }
                    {
                        IndexBuffer indexBuffer = this.IndexBuffer;
                        indexBuffer.Dispose();
                    }
                }
            }

            this.disposedValue = true;
        }
    }
}