flowchart
classDef c0001 color:#FF0000;
classDef c0010 stroke-dasharray: 10 10;
classDef c0011 stroke-dasharray: 10 10,color:#FF0000;
classDef c0100 fill:#BB66EE;
classDef c0101 fill:#BB66EE,color:#FF0000;
classDef c0110 fill:#BB66EE,stroke-dasharray: 10 10;
classDef c0111 fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
classDef c1000 stroke:#333,stroke-width:4px;
classDef c1001 stroke:#333,stroke-width:4px,color:#FF0000;
classDef c1010 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10;
classDef c1011 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10,color:#FF0000;
classDef c1100 stroke:#333,stroke-width:4px,fill:#BB66EE;
classDef c1101 stroke:#333,stroke-width:4px,fill:#BB66EE,color:#FF0000;
classDef c1110 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10;
classDef c1111 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
miniDFA0(["miniDFA0 1 DFA States"])
class miniDFA0 c1000;
miniDFA1(["miniDFA1 3 DFA States"])
miniDFA55(["miniDFA55 1 DFA States
AcceptToken '}'"])
class miniDFA55 c0001;
miniDFA56(["miniDFA56 1 DFA States
AcceptToken '{'"])
class miniDFA56 c0001;
miniDFA57(["miniDFA57 1 DFA States
AcceptToken ':'"])
class miniDFA57 c0001;
miniDFA58(["miniDFA58 1 DFA States
AcceptToken '?'"])
class miniDFA58 c0001;
miniDFA59(["miniDFA59 1 DFA States
AcceptToken '~'"])
class miniDFA59 c0001;
miniDFA60(["miniDFA60 1 DFA States
AcceptToken '.'"])
class miniDFA60 c0001;
miniDFA61(["miniDFA61 1 DFA States
AcceptToken ']'"])
class miniDFA61 c0001;
miniDFA62(["miniDFA62 1 DFA States
AcceptToken '['"])
class miniDFA62 c0001;
miniDFA63(["miniDFA63 1 DFA States
AcceptToken ';'"])
class miniDFA63 c0001;
miniDFA64(["miniDFA64 1 DFA States
AcceptToken ','"])
class miniDFA64 c0001;
miniDFA65(["miniDFA65 1 DFA States
AcceptToken ')'"])
class miniDFA65 c0001;
miniDFA66(["miniDFA66 1 DFA States
AcceptToken '('"])
class miniDFA66 c0001;
miniDFA67(["miniDFA67 1 DFA States
AcceptToken 'identifier'"])
class miniDFA67 c1001;
miniDFA68(["miniDFA68 1 DFA States
AcceptToken '='"])
class miniDFA68 c0001;
miniDFA69(["miniDFA69 1 DFA States
AcceptToken '%'"])
class miniDFA69 c0001;
miniDFA70(["miniDFA70 1 DFA States
AcceptToken '*'"])
class miniDFA70 c0001;
miniDFA71(["miniDFA71 1 DFA States
AcceptToken '!'"])
class miniDFA71 c0001;
miniDFA72(["miniDFA72 1 DFA States
AcceptToken 'identifier'"])
class miniDFA72 c1001;
miniDFA73(["miniDFA73 1 DFA States
AcceptToken 'identifier'"])
class miniDFA73 c1001;
miniDFA74(["miniDFA74 1 DFA States
AcceptToken 'identifier'"])
class miniDFA74 c1001;
miniDFA75(["miniDFA75 1 DFA States
AcceptToken '|'"])
class miniDFA75 c0001;
miniDFA76(["miniDFA76 1 DFA States
AcceptToken '^'"])
class miniDFA76 c0001;
miniDFA77(["miniDFA77 1 DFA States
AcceptToken '&'"])
class miniDFA77 c0001;
miniDFA78(["miniDFA78 1 DFA States
AcceptToken '>'"])
class miniDFA78 c0001;
miniDFA79(["miniDFA79 1 DFA States
AcceptToken '<'"])
class miniDFA79 c0001;
miniDFA80(["miniDFA80 1 DFA States
AcceptToken '/'"])
class miniDFA80 c0001;
miniDFA81(["miniDFA81 1 DFA States
AcceptToken 'number'
AcceptToken 'intConstant'
AcceptToken 'doubleConstant'"])
class miniDFA81 c0001;
miniDFA82(["miniDFA82 1 DFA States
AcceptToken 'number'
AcceptToken 'intConstant'
AcceptToken 'doubleConstant'"])
class miniDFA82 c0001;
miniDFA83(["miniDFA83 1 DFA States
AcceptToken '-'"])
class miniDFA83 c1001;
miniDFA84(["miniDFA84 1 DFA States
AcceptToken '+'"])
class miniDFA84 c1001;
miniDFA2(["miniDFA2 1 DFA States"])
miniDFA85(["miniDFA85 1 DFA States
AcceptToken 'literalString'"])
class miniDFA85 c0001;
miniDFA3(["miniDFA3 1 DFA States"])
miniDFA86(["miniDFA86 1 DFA States
AcceptToken 'identifier'"])
class miniDFA86 c0001;
miniDFA87(["miniDFA87 1 DFA States
AcceptToken '=='"])
class miniDFA87 c0001;
miniDFA88(["miniDFA88 1 DFA States
AcceptToken '%='"])
class miniDFA88 c0001;
miniDFA89(["miniDFA89 1 DFA States
AcceptToken '*='"])
class miniDFA89 c0001;
miniDFA90(["miniDFA90 1 DFA States
AcceptToken '!='"])
class miniDFA90 c0001;
miniDFA91(["miniDFA91 1 DFA States
AcceptToken 'identifier'"])
class miniDFA91 c0001;
miniDFA92(["miniDFA92 1 DFA States
AcceptToken 'identifier'"])
class miniDFA92 c0001;
miniDFA93(["miniDFA93 1 DFA States
AcceptToken 'identifier'"])
class miniDFA93 c0001;
miniDFA94(["miniDFA94 1 DFA States
AcceptToken '|='"])
class miniDFA94 c0001;
miniDFA95(["miniDFA95 1 DFA States
AcceptToken '||'"])
class miniDFA95 c0001;
miniDFA96(["miniDFA96 1 DFA States
AcceptToken '^='"])
class miniDFA96 c0001;
miniDFA97(["miniDFA97 1 DFA States
AcceptToken '^^'"])
class miniDFA97 c0001;
miniDFA98(["miniDFA98 1 DFA States
AcceptToken '&='"])
class miniDFA98 c0001;
miniDFA99(["miniDFA99 1 DFA States
AcceptToken '&&'"])
class miniDFA99 c0001;
miniDFA100(["miniDFA100 1 DFA States
AcceptToken '>='"])
class miniDFA100 c0001;
miniDFA101(["miniDFA101 1 DFA States
AcceptToken '>>'"])
class miniDFA101 c0001;
miniDFA102(["miniDFA102 1 DFA States
AcceptToken '<='"])
class miniDFA102 c0001;
miniDFA103(["miniDFA103 1 DFA States
AcceptToken '<<'"])
class miniDFA103 c0001;
miniDFA104(["miniDFA104 1 DFA States
AcceptToken 'inlineComment'"])
class miniDFA104 c0001;
miniDFA105(["miniDFA105 1 DFA States
AcceptToken '/='"])
class miniDFA105 c0001;
miniDFA106(["miniDFA106 1 DFA States
AcceptToken 'floatConstant'"])
class miniDFA106 c0001;
miniDFA107(["miniDFA107 1 DFA States
AcceptToken 'uintConstant'"])
class miniDFA107 c0001;
miniDFA4(["miniDFA4 1 DFA States"])
miniDFA108(["miniDFA108 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA108 c0001;
miniDFA5(["miniDFA5 1 DFA States"])
miniDFA109(["miniDFA109 1 DFA States
AcceptToken '-='"])
class miniDFA109 c0001;
miniDFA110(["miniDFA110 1 DFA States
AcceptToken '--'"])
class miniDFA110 c0001;
miniDFA111(["miniDFA111 1 DFA States
AcceptToken 'intConstant'
AcceptToken 'doubleConstant'"])
class miniDFA111 c0001;
miniDFA112(["miniDFA112 1 DFA States
AcceptToken '+='"])
class miniDFA112 c0001;
miniDFA113(["miniDFA113 1 DFA States
AcceptToken '++'"])
class miniDFA113 c0001;
miniDFA6(["miniDFA6 1 DFA States"])
miniDFA11(["miniDFA11 1 DFA States"])
miniDFA17(["miniDFA17 1 DFA States"])
miniDFA114(["miniDFA114 1 DFA States
AcceptToken '##'"])
class miniDFA114 c0001;
miniDFA20(["miniDFA20 1 DFA States"])
miniDFA12(["miniDFA12 1 DFA States"])
miniDFA24(["miniDFA24 1 DFA States"])
miniDFA25(["miniDFA25 1 DFA States"])
miniDFA115(["miniDFA115 1 DFA States
AcceptToken 'identifier'"])
class miniDFA115 c0001;
miniDFA116(["miniDFA116 1 DFA States
AcceptToken 'identifier'"])
class miniDFA116 c0001;
miniDFA117(["miniDFA117 1 DFA States
AcceptToken 'identifier'"])
class miniDFA117 c0001;
miniDFA118(["miniDFA118 1 DFA States
AcceptToken '>>='"])
class miniDFA118 c0001;
miniDFA119(["miniDFA119 1 DFA States
AcceptToken '<<='"])
class miniDFA119 c0001;
miniDFA120(["miniDFA120 1 DFA States
AcceptToken 'inlineComment'"])
class miniDFA120 c0001;
miniDFA121(["miniDFA121 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA121 c0001;
miniDFA26(["miniDFA26 1 DFA States"])
miniDFA122(["miniDFA122 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA122 c0001;
miniDFA123(["miniDFA123 1 DFA States
AcceptToken 'number'
AcceptToken 'doubleConstant'"])
class miniDFA123 c0001;
miniDFA124(["miniDFA124 1 DFA States
AcceptToken 'intConstant'"])
class miniDFA124 c0001;
miniDFA125(["miniDFA125 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA125 c0001;
miniDFA21(["miniDFA21 1 DFA States"])
miniDFA18(["miniDFA18 1 DFA States"])
miniDFA27(["miniDFA27 1 DFA States"])
miniDFA28(["miniDFA28 1 DFA States"])
miniDFA31(["miniDFA31 1 DFA States"])
miniDFA126(["miniDFA126 1 DFA States
AcceptToken '#if'"])
class miniDFA126 c0001;
miniDFA32(["miniDFA32 1 DFA States"])
miniDFA19(["miniDFA19 1 DFA States"])
miniDFA30(["miniDFA30 1 DFA States"])
miniDFA33(["miniDFA33 1 DFA States"])
miniDFA127(["miniDFA127 1 DFA States
AcceptToken 'identifier'"])
class miniDFA127 c0001;
miniDFA128(["miniDFA128 1 DFA States
AcceptToken 'identifier'"])
class miniDFA128 c0001;
miniDFA129(["miniDFA129 1 DFA States
AcceptToken 'identifier'"])
class miniDFA129 c0001;
miniDFA34(["miniDFA34 1 DFA States"])
miniDFA130(["miniDFA130 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA130 c0001;
miniDFA131(["miniDFA131 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA131 c0001;
miniDFA132(["miniDFA132 1 DFA States
AcceptToken 'uintConstant'"])
class miniDFA132 c0001;
miniDFA133(["miniDFA133 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA133 c0001;
miniDFA35(["miniDFA35 1 DFA States"])
miniDFA36(["miniDFA36 1 DFA States"])
miniDFA38(["miniDFA38 1 DFA States"])
miniDFA13(["miniDFA13 1 DFA States"])
miniDFA7(["miniDFA7 1 DFA States"])
miniDFA29(["miniDFA29 1 DFA States"])
miniDFA14(["miniDFA14 1 DFA States"])
miniDFA15(["miniDFA15 1 DFA States"])
miniDFA39(["miniDFA39 1 DFA States"])
miniDFA8(["miniDFA8 1 DFA States"])
miniDFA42(["miniDFA42 1 DFA States"])
miniDFA43(["miniDFA43 1 DFA States"])
miniDFA134(["miniDFA134 1 DFA States
AcceptToken 'identifier'"])
class miniDFA134 c0001;
miniDFA135(["miniDFA135 1 DFA States
AcceptToken 'boolConstant'"])
class miniDFA135 c0001;
miniDFA136(["miniDFA136 1 DFA States
AcceptToken 'identifier'"])
class miniDFA136 c0001;
miniDFA137(["miniDFA137 1 DFA States
AcceptToken 'doubleConstant'"])
class miniDFA137 c0001;
miniDFA44(["miniDFA44 1 DFA States"])
miniDFA138(["miniDFA138 1 DFA States
AcceptToken 'number'
AcceptToken 'doubleConstant'"])
class miniDFA138 c0001;
miniDFA139(["miniDFA139 1 DFA States
AcceptToken '#line'"])
class miniDFA139 c0001;
miniDFA9(["miniDFA9 1 DFA States"])
miniDFA45(["miniDFA45 1 DFA States"])
miniDFA46(["miniDFA46 1 DFA States"])
miniDFA22(["miniDFA22 1 DFA States"])
miniDFA16(["miniDFA16 1 DFA States"])
miniDFA47(["miniDFA47 1 DFA States"])
miniDFA23(["miniDFA23 1 DFA States"])
miniDFA48(["miniDFA48 1 DFA States"])
miniDFA49(["miniDFA49 1 DFA States"])
miniDFA140(["miniDFA140 1 DFA States
AcceptToken '#elif'"])
class miniDFA140 c0001;
miniDFA141(["miniDFA141 1 DFA States
AcceptToken '#else'"])
class miniDFA141 c0001;
miniDFA142(["miniDFA142 1 DFA States
AcceptToken 'boolConstant'"])
class miniDFA142 c0001;
miniDFA143(["miniDFA143 1 DFA States
AcceptToken 'identifier'"])
class miniDFA143 c0001;
miniDFA40(["miniDFA40 1 DFA States"])
miniDFA50(["miniDFA50 1 DFA States"])
miniDFA144(["miniDFA144 1 DFA States
AcceptToken '#undef'"])
class miniDFA144 c0001;
miniDFA51(["miniDFA51 1 DFA States"])
miniDFA52(["miniDFA52 1 DFA States"])
miniDFA145(["miniDFA145 1 DFA States
AcceptToken '#ifdef'"])
class miniDFA145 c0001;
miniDFA37(["miniDFA37 1 DFA States"])
miniDFA146(["miniDFA146 1 DFA States
AcceptToken '#error'"])
class miniDFA146 c0001;
miniDFA147(["miniDFA147 1 DFA States
AcceptToken '#endif'"])
class miniDFA147 c0001;
miniDFA148(["miniDFA148 1 DFA States
AcceptToken 'defined'
AcceptToken 'identifier'"])
class miniDFA148 c0001;
miniDFA53(["miniDFA53 1 DFA States"])
miniDFA149(["miniDFA149 1 DFA States
AcceptToken '#pragma'"])
class miniDFA149 c0001;
miniDFA150(["miniDFA150 1 DFA States
AcceptToken '#define'"])
class miniDFA150 c0001;
miniDFA151(["miniDFA151 1 DFA States
AcceptToken '#ifndef'"])
class miniDFA151 c0001;
miniDFA10(["miniDFA10 1 DFA States"])
miniDFA152(["miniDFA152 1 DFA States
AcceptToken '#version'"])
class miniDFA152 c0001;
miniDFA41(["miniDFA41 1 DFA States"])
miniDFA54(["miniDFA54 1 DFA States"])
miniDFA153(["miniDFA153 1 DFA States
AcceptToken '#extension'"])
class miniDFA153 c0001;
miniDFA0 -->|"#34;
BeginToken 'literalString' "|miniDFA1
miniDFA0 -->|"}
BeginToken '}' 
ExtendToken '}' "|miniDFA55
miniDFA0 -->|"#92;{
BeginToken '{' 
ExtendToken '{' "|miniDFA56
miniDFA0 -->|":
BeginToken ':' 
ExtendToken ':' "|miniDFA57
miniDFA0 -->|"#92;?
BeginToken '?' 
ExtendToken '?' "|miniDFA58
miniDFA0 -->|"~
BeginToken '~' 
ExtendToken '~' "|miniDFA59
miniDFA0 -->|"#92;.
BeginToken '.' 
ExtendToken '.' "|miniDFA60
miniDFA0 -->|"]
BeginToken ']' 
ExtendToken ']' "|miniDFA61
miniDFA0 -->|"#92;[
BeginToken '[' 
ExtendToken '[' "|miniDFA62
miniDFA0 -->|";
BeginToken ';' 
ExtendToken ';' "|miniDFA63
miniDFA0 -->|",
BeginToken ',' 
ExtendToken ',' "|miniDFA64
miniDFA0 -->|"#92;)
BeginToken ')' 
ExtendToken ')' "|miniDFA65
miniDFA0 -->|"#92;(
BeginToken '(' 
ExtendToken '(' "|miniDFA66
miniDFA0 -->|"[A-Z]_[a-c]e[g-s][u-z]
BeginToken 'identifier' 'literalString' 
ExtendToken 'identifier' "|miniDFA67
miniDFA0 -->|"=
BeginToken '==' '=' 
ExtendToken '=' "|miniDFA68
miniDFA0 -->|"%
BeginToken '%' '%=' 
ExtendToken '%' "|miniDFA69
miniDFA0 -->|"#92;#42;
BeginToken '#42;' '#42;=' 
ExtendToken '#42;' "|miniDFA70
miniDFA0 -->|"!
BeginToken '!' '!=' 
ExtendToken '!' "|miniDFA71
miniDFA0 -->|"f
BeginToken 'identifier' 'literalString' 'boolConstant' 
ExtendToken 'identifier' "|miniDFA72
miniDFA0 -->|"t
BeginToken 'identifier' 'literalString' 'boolConstant' 
ExtendToken 'identifier' "|miniDFA73
miniDFA0 -->|"d
BeginToken 'defined' 'identifier' 'literalString' 
ExtendToken 'identifier' "|miniDFA74
miniDFA0 -->|"#92;|
BeginToken '|' '||' '|=' 
ExtendToken '|' "|miniDFA75
miniDFA0 -->|"^
BeginToken '^' '^^' '^=' 
ExtendToken '^' "|miniDFA76
miniDFA0 -->|"&
BeginToken '&' '&&' '&=' 
ExtendToken '&' "|miniDFA77
miniDFA0 -->|">
BeginToken '>>' '>' '>=' '>>=' 
ExtendToken '>' "|miniDFA78
miniDFA0 -->|"#92;<
BeginToken '<<' '<' '<=' '<<=' 
ExtendToken '<' "|miniDFA79
miniDFA0 -->|"#92;/
BeginToken '/' '/=' 'inlineComment' 
ExtendToken '/' "|miniDFA80
miniDFA0 -->|"[1-9]
BeginToken 'number' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'number' 'intConstant' 'doubleConstant' "|miniDFA81
miniDFA0 -->|"0
BeginToken 'number' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'number' 'intConstant' 'doubleConstant' "|miniDFA82
miniDFA0 -->|"-
BeginToken '--' '-' '-=' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken '-' "|miniDFA83
miniDFA0 -->|"#92;+
BeginToken '++' '+' '+=' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken '+' "|miniDFA84
miniDFA0 -->|"#35;
BeginToken '#35;define' '#35;undef' '#35;#35;' '#35;if' '#35;ifdef' '#35;ifndef' '#35;else' '#35;elif' '#35;endif' '#35;error' '#35;pragma' '#35;extension' '#35;version' '#35;line' "|miniDFA2
miniDFA1 -->|"#34;
ExtendToken 'literalString' "|miniDFA85
miniDFA1 -->|"[^#92;#92;#34;]"|miniDFA1
miniDFA1 -->|"#92;#92;"|miniDFA3
miniDFA67 -->|"#34;
BeginToken 'literalString' "|miniDFA1
miniDFA67 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|miniDFA86
miniDFA68 -->|"=
ExtendToken '==' "|miniDFA87
miniDFA69 -->|"=
ExtendToken '%=' "|miniDFA88
miniDFA70 -->|"=
ExtendToken '#42;=' "|miniDFA89
miniDFA71 -->|"=
ExtendToken '!=' "|miniDFA90
miniDFA72 -->|"#34;
BeginToken 'literalString' "|miniDFA1
miniDFA72 -->|"[0-9][A-Z]_[b-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA72 -->|"a
ExtendToken 'identifier' "|miniDFA91
miniDFA73 -->|"#34;
BeginToken 'literalString' "|miniDFA1
miniDFA73 -->|"[0-9][A-Z]_[a-q][s-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA73 -->|"r
ExtendToken 'identifier' "|miniDFA92
miniDFA74 -->|"#34;
BeginToken 'literalString' "|miniDFA1
miniDFA74 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA74 -->|"e
ExtendToken 'identifier' "|miniDFA93
miniDFA75 -->|"=
ExtendToken '|=' "|miniDFA94
miniDFA75 -->|"#92;|
ExtendToken '||' "|miniDFA95
miniDFA76 -->|"=
ExtendToken '^=' "|miniDFA96
miniDFA76 -->|"^
ExtendToken '^^' "|miniDFA97
miniDFA77 -->|"=
ExtendToken '&=' "|miniDFA98
miniDFA77 -->|"&
ExtendToken '&&' "|miniDFA99
miniDFA78 -->|"=
ExtendToken '>=' "|miniDFA100
miniDFA78 -->|">
ExtendToken '>>' "|miniDFA101
miniDFA79 -->|"=
ExtendToken '<=' "|miniDFA102
miniDFA79 -->|"#92;<
ExtendToken '<<' "|miniDFA103
miniDFA80 -->|"#92;/
ExtendToken 'inlineComment' "|miniDFA104
miniDFA80 -->|"=
ExtendToken '/=' "|miniDFA105
miniDFA81 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA81 -->|"[uU]
ExtendToken 'uintConstant' "|miniDFA107
miniDFA81 -->|"[Ee]"|miniDFA4
miniDFA81 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA108
miniDFA81 -->|"[0-9]
ExtendToken 'number' 'intConstant' 'doubleConstant' "|miniDFA81
miniDFA82 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA82 -->|"[uU]
ExtendToken 'uintConstant' "|miniDFA107
miniDFA82 -->|"[Ee]"|miniDFA4
miniDFA82 -->|"x"|miniDFA5
miniDFA82 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA108
miniDFA82 -->|"[0-9]
ExtendToken 'number' 'intConstant' 'doubleConstant' "|miniDFA81
miniDFA83 -->|"=
ExtendToken '-=' "|miniDFA109
miniDFA83 -->|"-
ExtendToken '--' "|miniDFA110
miniDFA83 -->|"[0-9]
BeginToken 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'intConstant' 'doubleConstant' "|miniDFA111
miniDFA84 -->|"=
ExtendToken '+=' "|miniDFA112
miniDFA84 -->|"#92;+
ExtendToken '++' "|miniDFA113
miniDFA84 -->|"[0-9]
BeginToken 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'intConstant' 'doubleConstant' "|miniDFA111
miniDFA2 -->|"l"|miniDFA6
miniDFA2 -->|"v"|miniDFA11
miniDFA2 -->|"p"|miniDFA17
miniDFA2 -->|"#35;
ExtendToken '#35;#35;' "|miniDFA114
miniDFA2 -->|"u"|miniDFA20
miniDFA2 -->|"d"|miniDFA12
miniDFA2 -->|"i"|miniDFA24
miniDFA2 -->|"e"|miniDFA25
miniDFA3 -->|"[#32;-~]"|miniDFA1
miniDFA86 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|miniDFA86
miniDFA91 -->|"[0-9][A-Z]_[a-k][m-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA91 -->|"l
ExtendToken 'identifier' "|miniDFA115
miniDFA92 -->|"[0-9][A-Z]_[a-t][v-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA92 -->|"u
ExtendToken 'identifier' "|miniDFA116
miniDFA93 -->|"[0-9][A-Z]_[a-e][g-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA93 -->|"f
ExtendToken 'identifier' "|miniDFA117
miniDFA101 -->|"=
ExtendToken '>>=' "|miniDFA118
miniDFA103 -->|"=
ExtendToken '<<=' "|miniDFA119
miniDFA104 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment' "|miniDFA120
miniDFA4 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA121
miniDFA4 -->|"[-+]"|miniDFA26
miniDFA108 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA108 -->|"[Ee]"|miniDFA4
miniDFA108 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA122
miniDFA108 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|miniDFA123
miniDFA5 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant' "|miniDFA124
miniDFA111 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA111 -->|"[uU]
ExtendToken 'uintConstant' "|miniDFA107
miniDFA111 -->|"[Ee]"|miniDFA4
miniDFA111 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA125
miniDFA111 -->|"[0-9]
ExtendToken 'intConstant' 'doubleConstant' "|miniDFA111
miniDFA6 -->|"i"|miniDFA21
miniDFA11 -->|"e"|miniDFA18
miniDFA17 -->|"r"|miniDFA27
miniDFA20 -->|"n"|miniDFA28
miniDFA12 -->|"e"|miniDFA31
miniDFA24 -->|"f
ExtendToken '#35;if' "|miniDFA126
miniDFA25 -->|"x"|miniDFA32
miniDFA25 -->|"r"|miniDFA19
miniDFA25 -->|"n"|miniDFA30
miniDFA25 -->|"l"|miniDFA33
miniDFA115 -->|"[0-9][A-Z]_[a-r][t-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA115 -->|"s
ExtendToken 'identifier' "|miniDFA127
miniDFA116 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA116 -->|"e
ExtendToken 'identifier' 'boolConstant' "|miniDFA128
miniDFA117 -->|"[0-9][A-Z]_[a-h][j-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA117 -->|"i
ExtendToken 'identifier' "|miniDFA129
miniDFA120 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment' "|miniDFA120
miniDFA121 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA121 -->|"[Ee]"|miniDFA34
miniDFA121 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA121
miniDFA26 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA121
miniDFA122 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA122 -->|"[Ee]"|miniDFA4
miniDFA122 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA130
miniDFA123 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA123 -->|"[Ee]"|miniDFA4
miniDFA123 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA131
miniDFA123 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|miniDFA123
miniDFA124 -->|"[uU]
ExtendToken 'uintConstant' "|miniDFA132
miniDFA124 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant' "|miniDFA124
miniDFA125 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA125 -->|"[Ee]"|miniDFA4
miniDFA125 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA122
miniDFA125 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA133
miniDFA21 -->|"n"|miniDFA35
miniDFA18 -->|"r"|miniDFA36
miniDFA27 -->|"a"|miniDFA38
miniDFA28 -->|"d"|miniDFA13
miniDFA31 -->|"f"|miniDFA7
miniDFA126 -->|"n"|miniDFA29
miniDFA126 -->|"d"|miniDFA14
miniDFA32 -->|"t"|miniDFA15
miniDFA19 -->|"r"|miniDFA39
miniDFA30 -->|"d"|miniDFA8
miniDFA33 -->|"i"|miniDFA42
miniDFA33 -->|"s"|miniDFA43
miniDFA127 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA127 -->|"e
ExtendToken 'identifier' 'boolConstant' "|miniDFA134
miniDFA128 -->|"[^a-zA-Z0-9_]"|miniDFA135
miniDFA128 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|miniDFA86
miniDFA129 -->|"[0-9][A-Z]_[a-m][o-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA129 -->|"n
ExtendToken 'identifier' "|miniDFA136
miniDFA34 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA137
miniDFA34 -->|"[-+]"|miniDFA44
miniDFA130 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA130 -->|"[Ee]"|miniDFA4
miniDFA130 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA130
miniDFA131 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA131 -->|"[Ee]"|miniDFA4
miniDFA131 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|miniDFA138
miniDFA133 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA133 -->|"[Ee]"|miniDFA4
miniDFA133 -->|"[.]
ExtendToken 'doubleConstant' "|miniDFA122
miniDFA133 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA133
miniDFA35 -->|"e
ExtendToken '#35;line' "|miniDFA139
miniDFA36 -->|"s"|miniDFA9
miniDFA38 -->|"g"|miniDFA45
miniDFA13 -->|"e"|miniDFA46
miniDFA7 -->|"i"|miniDFA22
miniDFA29 -->|"d"|miniDFA16
miniDFA14 -->|"e"|miniDFA47
miniDFA15 -->|"e"|miniDFA23
miniDFA39 -->|"o"|miniDFA48
miniDFA8 -->|"i"|miniDFA49
miniDFA42 -->|"f
ExtendToken '#35;elif' "|miniDFA140
miniDFA43 -->|"e
ExtendToken '#35;else' "|miniDFA141
miniDFA134 -->|"[^a-zA-Z0-9_]"|miniDFA142
miniDFA134 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|miniDFA86
miniDFA136 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA136 -->|"e
ExtendToken 'identifier' "|miniDFA143
miniDFA137 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA137 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA137
miniDFA44 -->|"[0-9]
ExtendToken 'doubleConstant' "|miniDFA137
miniDFA138 -->|"[fF]
ExtendToken 'floatConstant' "|miniDFA106
miniDFA138 -->|"[Ee]"|miniDFA4
miniDFA138 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|miniDFA138
miniDFA9 -->|"i"|miniDFA40
miniDFA45 -->|"m"|miniDFA50
miniDFA46 -->|"f
ExtendToken '#35;undef' "|miniDFA144
miniDFA22 -->|"n"|miniDFA51
miniDFA16 -->|"e"|miniDFA52
miniDFA47 -->|"f
ExtendToken '#35;ifdef' "|miniDFA145
miniDFA23 -->|"n"|miniDFA37
miniDFA48 -->|"r
ExtendToken '#35;error' "|miniDFA146
miniDFA49 -->|"f
ExtendToken '#35;endif' "|miniDFA147
miniDFA143 -->|"[0-9][A-Z]_[a-c][e-z]
ExtendToken 'identifier' "|miniDFA86
miniDFA143 -->|"d
ExtendToken 'defined' 'identifier' "|miniDFA148
miniDFA40 -->|"o"|miniDFA53
miniDFA50 -->|"a
ExtendToken '#35;pragma' "|miniDFA149
miniDFA51 -->|"e
ExtendToken '#35;define' "|miniDFA150
miniDFA52 -->|"f
ExtendToken '#35;ifndef' "|miniDFA151
miniDFA37 -->|"s"|miniDFA10
miniDFA148 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|miniDFA86
miniDFA53 -->|"n
ExtendToken '#35;version' "|miniDFA152
miniDFA10 -->|"i"|miniDFA41
miniDFA41 -->|"o"|miniDFA54
miniDFA54 -->|"n
ExtendToken '#35;extension' "|miniDFA153
