flowchart
classDef c0001 color:#FF0000;
classDef c0010 stroke-dasharray: 10 10;
classDef c0011 stroke-dasharray: 10 10,color:#FF0000;
classDef c0100 fill:#BB66EE;
classDef c0101 fill:#BB66EE,color:#FF0000;
classDef c0110 fill:#BB66EE,stroke-dasharray: 10 10;
classDef c0111 fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
classDef c1000 stroke:#333,stroke-width:4px;
classDef c1001 stroke:#333,stroke-width:4px,color:#FF0000;
classDef c1010 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10;
classDef c1011 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10,color:#FF0000;
classDef c1100 stroke:#333,stroke-width:4px,fill:#BB66EE;
classDef c1101 stroke:#333,stroke-width:4px,fill:#BB66EE,color:#FF0000;
classDef c1110 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10;
classDef c1111 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
subgraph DFA0["DFA0 wholeStart"]
NFA0_0_0("NFA0-0 wholeStart")
class NFA0_0_0 c1000;
end
class DFA0 c1000;
subgraph DFA1["DFA1 1 NFA States"]
NFA62_3_1("NFA62-3 char[1]")
end
subgraph DFA2["DFA2 1 NFA States"]
NFA47_1_2[\"NFA47-1 char[1]
AcceptToken '}'"/]
class NFA47_1_2 c0001;
end
class DFA2 c0001;
subgraph DFA3["DFA3 1 NFA States"]
NFA46_1_3[\"NFA46-1 char[1]
AcceptToken '{'"/]
class NFA46_1_3 c0001;
end
class DFA3 c0001;
subgraph DFA4["DFA4 1 NFA States"]
NFA34_1_4[\"NFA34-1 char[1]
AcceptToken ':'"/]
class NFA34_1_4 c0001;
end
class DFA4 c0001;
subgraph DFA5["DFA5 1 NFA States"]
NFA33_1_5[\"NFA33-1 char[1]
AcceptToken '?'"/]
class NFA33_1_5 c0001;
end
class DFA5 c0001;
subgraph DFA6["DFA6 1 NFA States"]
NFA15_1_6[\"NFA15-1 char[1]
AcceptToken '~'"/]
class NFA15_1_6 c0001;
end
class DFA6 c0001;
subgraph DFA7["DFA7 1 NFA States"]
NFA9_1_7[\"NFA9-1 char[1]
AcceptToken '.'"/]
class NFA9_1_7 c0001;
end
class DFA7 c0001;
subgraph DFA8["DFA8 1 NFA States"]
NFA8_1_8[\"NFA8-1 char[1]
AcceptToken ']'"/]
class NFA8_1_8 c0001;
end
class DFA8 c0001;
subgraph DFA9["DFA9 1 NFA States"]
NFA7_1_9[\"NFA7-1 char[1]
AcceptToken '['"/]
class NFA7_1_9 c0001;
end
class DFA9 c0001;
subgraph DFA10["DFA10 1 NFA States"]
NFA6_1_10[\"NFA6-1 char[1]
AcceptToken ';'"/]
class NFA6_1_10 c0001;
end
class DFA10 c0001;
subgraph DFA11["DFA11 1 NFA States"]
NFA5_1_11[\"NFA5-1 char[1]
AcceptToken ','"/]
class NFA5_1_11 c0001;
end
class DFA11 c0001;
subgraph DFA12["DFA12 1 NFA States"]
NFA3_1_12[\"NFA3-1 char[1]
AcceptToken ')'"/]
class NFA3_1_12 c0001;
end
class DFA12 c0001;
subgraph DFA13["DFA13 1 NFA States"]
NFA2_1_13[\"NFA2-1 char[1]
AcceptToken '('"/]
class NFA2_1_13 c0001;
end
class DFA13 c0001;
subgraph DFA14["DFA14 2 NFA States"]
NFA61_1_14[\"NFA61-1 scope[1]
AcceptToken 'identifier'"/]
class NFA61_1_14 c0001;
NFA62_1_15("NFA62-1 scope[1]")
class NFA62_1_15 c1000;
end
class DFA14 c1001;
subgraph DFA15["DFA15 2 NFA States"]
NFA25_1_16("NFA25-1 char[1]")
NFA35_1_17[\"NFA35-1 char[1]
AcceptToken '='"/]
class NFA35_1_17 c0001;
end
class DFA15 c0001;
subgraph DFA16["DFA16 2 NFA States"]
NFA18_1_18[\"NFA18-1 char[1]
AcceptToken '%'"/]
class NFA18_1_18 c0001;
NFA38_1_19("NFA38-1 char[1]")
end
class DFA16 c0001;
subgraph DFA17["DFA17 2 NFA States"]
NFA16_1_20[\"NFA16-1 char[1]
AcceptToken '*'"/]
class NFA16_1_20 c0001;
NFA36_1_21("NFA36-1 char[1]")
end
class DFA17 c0001;
subgraph DFA18["DFA18 2 NFA States"]
NFA14_1_22[\"NFA14-1 char[1]
AcceptToken '!'"/]
class NFA14_1_22 c0001;
NFA26_1_23("NFA26-1 char[1]")
end
class DFA18 c0001;
subgraph DFA19["DFA19 3 NFA States"]
NFA61_1_24[\"NFA61-1 scope[1]
AcceptToken 'identifier'"/]
class NFA61_1_24 c0001;
NFA62_1_25("NFA62-1 scope[1]")
class NFA62_1_25 c1000;
NFA70_1_26("NFA70-1 char[1]")
end
class DFA19 c1001;
subgraph DFA20["DFA20 3 NFA States"]
NFA61_1_27[\"NFA61-1 scope[1]
AcceptToken 'identifier'"/]
class NFA61_1_27 c0001;
NFA62_1_28("NFA62-1 scope[1]")
class NFA62_1_28 c1000;
NFA69_1_29("NFA69-1 char[1]")
end
class DFA20 c1001;
subgraph DFA21["DFA21 3 NFA States"]
NFA60_1_30("NFA60-1 char[1]")
NFA61_1_31[\"NFA61-1 scope[1]
AcceptToken 'identifier'"/]
class NFA61_1_31 c0001;
NFA62_1_32("NFA62-1 scope[1]")
class NFA62_1_32 c1000;
end
class DFA21 c1001;
subgraph DFA22["DFA22 3 NFA States"]
NFA29_1_33[\"NFA29-1 char[1]
AcceptToken '|'"/]
class NFA29_1_33 c0001;
NFA32_1_34("NFA32-1 char[1]")
NFA45_1_35("NFA45-1 char[1]")
end
class DFA22 c0001;
subgraph DFA23["DFA23 3 NFA States"]
NFA28_1_36[\"NFA28-1 char[1]
AcceptToken '^'"/]
class NFA28_1_36 c0001;
NFA31_1_37("NFA31-1 char[1]")
NFA44_1_38("NFA44-1 char[1]")
end
class DFA23 c0001;
subgraph DFA24["DFA24 3 NFA States"]
NFA27_1_39[\"NFA27-1 char[1]
AcceptToken '&'"/]
class NFA27_1_39 c0001;
NFA30_1_40("NFA30-1 char[1]")
NFA43_1_41("NFA43-1 char[1]")
end
class DFA24 c0001;
subgraph DFA25["DFA25 4 NFA States"]
NFA20_1_42("NFA20-1 char[1]")
NFA22_1_43[\"NFA22-1 char[1]
AcceptToken '>'"/]
class NFA22_1_43 c0001;
NFA24_1_44("NFA24-1 char[1]")
NFA42_1_45("NFA42-1 char[1]")
end
class DFA25 c0001;
subgraph DFA26["DFA26 4 NFA States"]
NFA19_1_46("NFA19-1 char[1]")
NFA21_1_47[\"NFA21-1 char[1]
AcceptToken '<'"/]
class NFA21_1_47 c0001;
NFA23_1_48("NFA23-1 char[1]")
NFA41_1_49("NFA41-1 char[1]")
end
class DFA26 c0001;
subgraph DFA27["DFA27 3 NFA States"]
NFA17_1_50[\"NFA17-1 char[1]
AcceptToken '/'"/]
class NFA17_1_50 c0001;
NFA37_1_51("NFA37-1 char[1]")
NFA72_1_52("NFA72-1 char[1]")
end
class DFA27 c0001;
subgraph DFA28["DFA28 5 NFA States"]
NFA63_1_53[\"NFA63-1 scope[1]
AcceptToken 'number'"/]
class NFA63_1_53 c0001;
NFA64_3_54[\"NFA64-3 scope[1]
AcceptToken 'intConstant'"/]
class NFA64_3_54 c0001;
NFA66_3_55("NFA66-3 scope[1]")
NFA68_3_56("NFA68-3 scope[1]")
NFA71_3_57[\"NFA71-3 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_3_57 c0001;
end
class DFA28 c0001;
subgraph DFA29["DFA29 7 NFA States"]
NFA63_1_58[\"NFA63-1 scope[1]
AcceptToken 'number'"/]
class NFA63_1_58 c0001;
NFA65_1_59("NFA65-1 char[1]")
NFA67_1_60("NFA67-1 char[1]")
NFA64_3_61[\"NFA64-3 scope[1]
AcceptToken 'intConstant'"/]
class NFA64_3_61 c0001;
NFA66_3_62("NFA66-3 scope[1]")
NFA68_3_63("NFA68-3 scope[1]")
NFA71_3_64[\"NFA71-3 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_3_64 c0001;
end
class DFA29 c0001;
subgraph DFA30["DFA30 7 NFA States"]
NFA11_1_65("NFA11-1 char[1]")
NFA13_1_66[\"NFA13-1 char[1]
AcceptToken '-'"/]
class NFA13_1_66 c0001;
NFA40_1_67("NFA40-1 char[1]")
NFA64_1_68("NFA64-1 scope[1]")
class NFA64_1_68 c1000;
NFA66_1_69("NFA66-1 scope[1]")
class NFA66_1_69 c1000;
NFA68_1_70("NFA68-1 scope[1]")
class NFA68_1_70 c1000;
NFA71_1_71("NFA71-1 scope[1]")
class NFA71_1_71 c1000;
end
class DFA30 c1001;
subgraph DFA31["DFA31 7 NFA States"]
NFA10_1_72("NFA10-1 char[1]")
NFA12_1_73[\"NFA12-1 char[1]
AcceptToken '+'"/]
class NFA12_1_73 c0001;
NFA39_1_74("NFA39-1 char[1]")
NFA64_1_75("NFA64-1 scope[1]")
class NFA64_1_75 c1000;
NFA66_1_76("NFA66-1 scope[1]")
class NFA66_1_76 c1000;
NFA68_1_77("NFA68-1 scope[1]")
class NFA68_1_77 c1000;
NFA71_1_78("NFA71-1 scope[1]")
class NFA71_1_78 c1000;
end
class DFA31 c1001;
subgraph DFA32["DFA32 14 NFA States"]
NFA1_1_79("NFA1-1 char[1]")
NFA4_1_80("NFA4-1 char[1]")
NFA48_1_81("NFA48-1 char[1]")
NFA49_1_82("NFA49-1 char[1]")
NFA50_1_83("NFA50-1 char[1]")
NFA51_1_84("NFA51-1 char[1]")
NFA52_1_85("NFA52-1 char[1]")
NFA53_1_86("NFA53-1 char[1]")
NFA54_1_87("NFA54-1 char[1]")
NFA55_1_88("NFA55-1 char[1]")
NFA56_1_89("NFA56-1 char[1]")
NFA57_1_90("NFA57-1 char[1]")
NFA58_1_91("NFA58-1 char[1]")
NFA59_1_92("NFA59-1 char[1]")
end
subgraph DFA33["DFA33 1 NFA States"]
NFA62_13_93[\"NFA62-13 char[1]
AcceptToken 'literalString'"/]
class NFA62_13_93 c0001;
end
class DFA33 c0001;
subgraph DFA34["DFA34 1 NFA States"]
NFA62_11_94("NFA62-11 scope[1]")
end
subgraph DFA35["DFA35 1 NFA States"]
NFA62_5_95("NFA62-5 char[1]")
end
subgraph DFA36["DFA36 1 NFA States"]
NFA61_2_96[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_96 c0001;
end
class DFA36 c0001;
subgraph DFA37["DFA37 1 NFA States"]
NFA25_3_97[\"NFA25-3 char[1]
AcceptToken '=='"/]
class NFA25_3_97 c0001;
end
class DFA37 c0001;
subgraph DFA38["DFA38 1 NFA States"]
NFA38_3_98[\"NFA38-3 char[1]
AcceptToken '%='"/]
class NFA38_3_98 c0001;
end
class DFA38 c0001;
subgraph DFA39["DFA39 1 NFA States"]
NFA36_3_99[\"NFA36-3 char[1]
AcceptToken '*='"/]
class NFA36_3_99 c0001;
end
class DFA39 c0001;
subgraph DFA40["DFA40 1 NFA States"]
NFA26_3_100[\"NFA26-3 char[1]
AcceptToken '!='"/]
class NFA26_3_100 c0001;
end
class DFA40 c0001;
subgraph DFA41["DFA41 2 NFA States"]
NFA61_2_101[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_101 c0001;
NFA70_3_102("NFA70-3 char[1]")
end
class DFA41 c0001;
subgraph DFA42["DFA42 2 NFA States"]
NFA61_2_103[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_103 c0001;
NFA69_3_104("NFA69-3 char[1]")
end
class DFA42 c0001;
subgraph DFA43["DFA43 2 NFA States"]
NFA60_3_105("NFA60-3 char[1]")
NFA61_2_106[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_106 c0001;
end
class DFA43 c0001;
subgraph DFA44["DFA44 1 NFA States"]
NFA45_3_107[\"NFA45-3 char[1]
AcceptToken '|='"/]
class NFA45_3_107 c0001;
end
class DFA44 c0001;
subgraph DFA45["DFA45 1 NFA States"]
NFA32_3_108[\"NFA32-3 char[1]
AcceptToken '||'"/]
class NFA32_3_108 c0001;
end
class DFA45 c0001;
subgraph DFA46["DFA46 1 NFA States"]
NFA44_3_109[\"NFA44-3 char[1]
AcceptToken '^='"/]
class NFA44_3_109 c0001;
end
class DFA46 c0001;
subgraph DFA47["DFA47 1 NFA States"]
NFA31_3_110[\"NFA31-3 char[1]
AcceptToken '^^'"/]
class NFA31_3_110 c0001;
end
class DFA47 c0001;
subgraph DFA48["DFA48 1 NFA States"]
NFA43_3_111[\"NFA43-3 char[1]
AcceptToken '&='"/]
class NFA43_3_111 c0001;
end
class DFA48 c0001;
subgraph DFA49["DFA49 1 NFA States"]
NFA30_3_112[\"NFA30-3 char[1]
AcceptToken '&&'"/]
class NFA30_3_112 c0001;
end
class DFA49 c0001;
subgraph DFA50["DFA50 1 NFA States"]
NFA24_3_113[\"NFA24-3 char[1]
AcceptToken '>='"/]
class NFA24_3_113 c0001;
end
class DFA50 c0001;
subgraph DFA51["DFA51 2 NFA States"]
NFA20_3_114[\"NFA20-3 char[1]
AcceptToken '>>'"/]
class NFA20_3_114 c0001;
NFA42_3_115("NFA42-3 char[1]")
end
class DFA51 c0001;
subgraph DFA52["DFA52 1 NFA States"]
NFA23_3_116[\"NFA23-3 char[1]
AcceptToken '<='"/]
class NFA23_3_116 c0001;
end
class DFA52 c0001;
subgraph DFA53["DFA53 2 NFA States"]
NFA19_3_117[\"NFA19-3 char[1]
AcceptToken '<<'"/]
class NFA19_3_117 c0001;
NFA41_3_118("NFA41-3 char[1]")
end
class DFA53 c0001;
subgraph DFA54["DFA54 1 NFA States"]
NFA72_3_119[\"NFA72-3 char[1]
AcceptToken 'inlineComment'"/]
class NFA72_3_119 c0001;
end
class DFA54 c0001;
subgraph DFA55["DFA55 1 NFA States"]
NFA37_3_120[\"NFA37-3 char[1]
AcceptToken '/='"/]
class NFA37_3_120 c0001;
end
class DFA55 c0001;
subgraph DFA56["DFA56 1 NFA States"]
NFA68_18_121[\"NFA68-18 scope[1]
AcceptToken 'floatConstant'"/]
class NFA68_18_121 c0001;
end
class DFA56 c0001;
subgraph DFA57["DFA57 1 NFA States"]
NFA66_5_122[\"NFA66-5 scope[1]
AcceptToken 'uintConstant'"/]
class NFA66_5_122 c0001;
end
class DFA57 c0001;
subgraph DFA58["DFA58 2 NFA States"]
NFA68_10_123("NFA68-10 scope[1]")
NFA71_10_124("NFA71-10 scope[1]")
end
subgraph DFA59["DFA59 3 NFA States"]
NFA63_3_125("NFA63-3 scope[1]")
NFA68_5_126("NFA68-5 scope[1]")
NFA71_5_127[\"NFA71-5 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_5_127 c0001;
end
class DFA59 c0001;
subgraph DFA60["DFA60 2 NFA States"]
NFA65_3_128("NFA65-3 char[1]")
NFA67_3_129("NFA67-3 char[1]")
end
subgraph DFA61["DFA61 1 NFA States"]
NFA40_3_130[\"NFA40-3 char[1]
AcceptToken '-='"/]
class NFA40_3_130 c0001;
end
class DFA61 c0001;
subgraph DFA62["DFA62 1 NFA States"]
NFA11_3_131[\"NFA11-3 char[1]
AcceptToken '--'"/]
class NFA11_3_131 c0001;
end
class DFA62 c0001;
subgraph DFA63["DFA63 4 NFA States"]
NFA64_3_132[\"NFA64-3 scope[1]
AcceptToken 'intConstant'"/]
class NFA64_3_132 c0001;
NFA66_3_133("NFA66-3 scope[1]")
NFA68_3_134("NFA68-3 scope[1]")
NFA71_3_135[\"NFA71-3 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_3_135 c0001;
end
class DFA63 c0001;
subgraph DFA64["DFA64 1 NFA States"]
NFA39_3_136[\"NFA39-3 char[1]
AcceptToken '+='"/]
class NFA39_3_136 c0001;
end
class DFA64 c0001;
subgraph DFA65["DFA65 1 NFA States"]
NFA10_3_137[\"NFA10-3 char[1]
AcceptToken '++'"/]
class NFA10_3_137 c0001;
end
class DFA65 c0001;
subgraph DFA66["DFA66 1 NFA States"]
NFA59_3_138("NFA59-3 char[1]")
end
subgraph DFA67["DFA67 1 NFA States"]
NFA58_3_139("NFA58-3 char[1]")
end
subgraph DFA68["DFA68 1 NFA States"]
NFA56_3_140("NFA56-3 char[1]")
end
subgraph DFA69["DFA69 1 NFA States"]
NFA48_3_141[\"NFA48-3 char[1]
AcceptToken '##'"/]
class NFA48_3_141 c0001;
end
class DFA69 c0001;
subgraph DFA70["DFA70 1 NFA States"]
NFA4_3_142("NFA4-3 char[1]")
end
subgraph DFA71["DFA71 1 NFA States"]
NFA1_3_143("NFA1-3 char[1]")
end
subgraph DFA72["DFA72 3 NFA States"]
NFA49_3_144("NFA49-3 char[1]")
NFA50_3_145("NFA50-3 char[1]")
NFA51_3_146("NFA51-3 char[1]")
end
subgraph DFA73["DFA73 5 NFA States"]
NFA52_3_147("NFA52-3 char[1]")
NFA53_3_148("NFA53-3 char[1]")
NFA54_3_149("NFA54-3 char[1]")
NFA55_3_150("NFA55-3 char[1]")
NFA57_3_151("NFA57-3 char[1]")
end
subgraph DFA74["DFA74 1 NFA States"]
NFA62_7_152("NFA62-7 char[1]")
end
subgraph DFA75["DFA75 2 NFA States"]
NFA61_2_153[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_153 c0001;
NFA70_5_154("NFA70-5 char[1]")
end
class DFA75 c0001;
subgraph DFA76["DFA76 2 NFA States"]
NFA61_2_155[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_155 c0001;
NFA69_5_156("NFA69-5 char[1]")
end
class DFA76 c0001;
subgraph DFA77["DFA77 2 NFA States"]
NFA60_5_157("NFA60-5 char[1]")
NFA61_2_158[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_158 c0001;
end
class DFA77 c0001;
subgraph DFA78["DFA78 1 NFA States"]
NFA42_5_159[\"NFA42-5 char[1]
AcceptToken '>>='"/]
class NFA42_5_159 c0001;
end
class DFA78 c0001;
subgraph DFA79["DFA79 1 NFA States"]
NFA41_5_160[\"NFA41-5 char[1]
AcceptToken '<<='"/]
class NFA41_5_160 c0001;
end
class DFA79 c0001;
subgraph DFA80["DFA80 1 NFA States"]
NFA72_4_161[\"NFA72-4 scope{0, -1}
AcceptToken 'inlineComment'"/]
class NFA72_4_161 c0001;
end
class DFA80 c0001;
subgraph DFA81["DFA81 2 NFA States"]
NFA68_14_162("NFA68-14 scope[1]")
NFA71_14_163[\"NFA71-14 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_14_163 c0001;
end
class DFA81 c0001;
subgraph DFA82["DFA82 2 NFA States"]
NFA68_12_164("NFA68-12 scope[1]")
NFA71_12_165("NFA71-12 scope[1]")
end
subgraph DFA83["DFA83 2 NFA States"]
NFA68_5_166("NFA68-5 scope[1]")
NFA71_5_167[\"NFA71-5 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_5_167 c0001;
end
class DFA83 c0001;
subgraph DFA84["DFA84 3 NFA States"]
NFA63_5_168[\"NFA63-5 scope[1]
AcceptToken 'number'"/]
class NFA63_5_168 c0001;
NFA68_6_169("NFA68-6 scope{0, -1}")
NFA71_6_170[\"NFA71-6 scope{0, -1}
AcceptToken 'doubleConstant'"/]
class NFA71_6_170 c0001;
end
class DFA84 c0001;
subgraph DFA85["DFA85 2 NFA States"]
NFA65_5_171[\"NFA65-5 scope[1]
AcceptToken 'intConstant'"/]
class NFA65_5_171 c0001;
NFA67_5_172("NFA67-5 scope[1]")
end
class DFA85 c0001;
subgraph DFA86["DFA86 2 NFA States"]
NFA68_5_173("NFA68-5 scope[1]")
NFA71_5_174[\"NFA71-5 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_5_174 c0001;
end
class DFA86 c0001;
subgraph DFA87["DFA87 1 NFA States"]
NFA59_5_175("NFA59-5 char[1]")
end
subgraph DFA88["DFA88 1 NFA States"]
NFA58_5_176("NFA58-5 char[1]")
end
subgraph DFA89["DFA89 1 NFA States"]
NFA56_5_177("NFA56-5 char[1]")
end
subgraph DFA90["DFA90 1 NFA States"]
NFA4_5_178("NFA4-5 char[1]")
end
subgraph DFA91["DFA91 1 NFA States"]
NFA1_5_179("NFA1-5 char[1]")
end
subgraph DFA92["DFA92 3 NFA States"]
NFA49_5_180[\"NFA49-5 char[1]
AcceptToken '#if'"/]
class NFA49_5_180 c0001;
NFA50_5_181("NFA50-5 char[1]")
NFA51_5_182("NFA51-5 char[1]")
end
class DFA92 c0001;
subgraph DFA93["DFA93 1 NFA States"]
NFA57_5_183("NFA57-5 char[1]")
end
subgraph DFA94["DFA94 1 NFA States"]
NFA55_5_184("NFA55-5 char[1]")
end
subgraph DFA95["DFA95 1 NFA States"]
NFA54_5_185("NFA54-5 char[1]")
end
subgraph DFA96["DFA96 2 NFA States"]
NFA52_5_186("NFA52-5 char[1]")
NFA53_5_187("NFA53-5 char[1]")
end
subgraph DFA97["DFA97 2 NFA States"]
NFA61_2_188[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_188 c0001;
NFA70_7_189("NFA70-7 char[1]")
end
class DFA97 c0001;
subgraph DFA98["DFA98 2 NFA States"]
NFA61_2_190[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_190 c0001;
NFA69_7_191("NFA69-7 char[1]")
end
class DFA98 c0001;
subgraph DFA99["DFA99 2 NFA States"]
NFA60_7_192("NFA60-7 char[1]")
NFA61_2_193[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_193 c0001;
end
class DFA99 c0001;
subgraph DFA100["DFA100 2 NFA States"]
NFA68_10_194("NFA68-10 scope[1]")
NFA71_10_195("NFA71-10 scope[1]")
end
subgraph DFA101["DFA101 2 NFA States"]
NFA68_6_196("NFA68-6 scope{0, -1}")
NFA71_6_197[\"NFA71-6 scope{0, -1}
AcceptToken 'doubleConstant'"/]
class NFA71_6_197 c0001;
end
class DFA101 c0001;
subgraph DFA102["DFA102 3 NFA States"]
NFA63_3_198("NFA63-3 scope[1]")
NFA68_5_199("NFA68-5 scope[1]")
NFA71_5_200[\"NFA71-5 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_5_200 c0001;
end
class DFA102 c0001;
subgraph DFA103["DFA103 1 NFA States"]
NFA67_7_201[\"NFA67-7 scope[1]
AcceptToken 'uintConstant'"/]
class NFA67_7_201 c0001;
end
class DFA103 c0001;
subgraph DFA104["DFA104 2 NFA States"]
NFA68_6_202("NFA68-6 scope{0, -1}")
NFA71_6_203[\"NFA71-6 scope{0, -1}
AcceptToken 'doubleConstant'"/]
class NFA71_6_203 c0001;
end
class DFA104 c0001;
subgraph DFA105["DFA105 1 NFA States"]
NFA59_7_204("NFA59-7 char[1]")
end
subgraph DFA106["DFA106 1 NFA States"]
NFA58_7_205("NFA58-7 char[1]")
end
subgraph DFA107["DFA107 1 NFA States"]
NFA56_7_206("NFA56-7 char[1]")
end
subgraph DFA108["DFA108 1 NFA States"]
NFA4_7_207("NFA4-7 char[1]")
end
subgraph DFA109["DFA109 1 NFA States"]
NFA1_7_208("NFA1-7 char[1]")
end
subgraph DFA110["DFA110 1 NFA States"]
NFA51_7_209("NFA51-7 char[1]")
end
subgraph DFA111["DFA111 1 NFA States"]
NFA50_7_210("NFA50-7 char[1]")
end
subgraph DFA112["DFA112 1 NFA States"]
NFA57_7_211("NFA57-7 char[1]")
end
subgraph DFA113["DFA113 1 NFA States"]
NFA55_7_212("NFA55-7 char[1]")
end
subgraph DFA114["DFA114 1 NFA States"]
NFA54_7_213("NFA54-7 char[1]")
end
subgraph DFA115["DFA115 1 NFA States"]
NFA53_7_214("NFA53-7 char[1]")
end
subgraph DFA116["DFA116 1 NFA States"]
NFA52_7_215("NFA52-7 char[1]")
end
subgraph DFA117["DFA117 2 NFA States"]
NFA61_2_216[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_216 c0001;
NFA70_9_217("NFA70-9 char[1]")
end
class DFA117 c0001;
subgraph DFA118["DFA118 1 NFA States"]
NFA69_11_218[\"NFA69-11 scope[1]
AcceptToken 'boolConstant'"/]
class NFA69_11_218 c0001;
end
class DFA118 c0001;
subgraph DFA119["DFA119 2 NFA States"]
NFA60_9_219("NFA60-9 char[1]")
NFA61_2_220[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_220 c0001;
end
class DFA119 c0001;
subgraph DFA120["DFA120 2 NFA States"]
NFA68_14_221("NFA68-14 scope[1]")
NFA71_14_222[\"NFA71-14 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_14_222 c0001;
end
class DFA120 c0001;
subgraph DFA121["DFA121 2 NFA States"]
NFA68_12_223("NFA68-12 scope[1]")
NFA71_12_224("NFA71-12 scope[1]")
end
subgraph DFA122["DFA122 3 NFA States"]
NFA63_5_225[\"NFA63-5 scope[1]
AcceptToken 'number'"/]
class NFA63_5_225 c0001;
NFA68_6_226("NFA68-6 scope{0, -1}")
NFA71_6_227[\"NFA71-6 scope{0, -1}
AcceptToken 'doubleConstant'"/]
class NFA71_6_227 c0001;
end
class DFA122 c0001;
subgraph DFA123["DFA123 1 NFA States"]
NFA59_9_228[\"NFA59-9 char[1]
AcceptToken '#line'"/]
class NFA59_9_228 c0001;
end
class DFA123 c0001;
subgraph DFA124["DFA124 1 NFA States"]
NFA58_9_229("NFA58-9 char[1]")
end
subgraph DFA125["DFA125 1 NFA States"]
NFA56_9_230("NFA56-9 char[1]")
end
subgraph DFA126["DFA126 1 NFA States"]
NFA4_9_231("NFA4-9 char[1]")
end
subgraph DFA127["DFA127 1 NFA States"]
NFA1_9_232("NFA1-9 char[1]")
end
subgraph DFA128["DFA128 1 NFA States"]
NFA51_9_233("NFA51-9 char[1]")
end
subgraph DFA129["DFA129 1 NFA States"]
NFA50_9_234("NFA50-9 char[1]")
end
subgraph DFA130["DFA130 1 NFA States"]
NFA57_9_235("NFA57-9 char[1]")
end
subgraph DFA131["DFA131 1 NFA States"]
NFA55_9_236("NFA55-9 char[1]")
end
subgraph DFA132["DFA132 1 NFA States"]
NFA54_9_237("NFA54-9 char[1]")
end
subgraph DFA133["DFA133 1 NFA States"]
NFA53_9_238[\"NFA53-9 char[1]
AcceptToken '#elif'"/]
class NFA53_9_238 c0001;
end
class DFA133 c0001;
subgraph DFA134["DFA134 1 NFA States"]
NFA52_9_239[\"NFA52-9 char[1]
AcceptToken '#else'"/]
class NFA52_9_239 c0001;
end
class DFA134 c0001;
subgraph DFA135["DFA135 1 NFA States"]
NFA70_13_240[\"NFA70-13 scope[1]
AcceptToken 'boolConstant'"/]
class NFA70_13_240 c0001;
end
class DFA135 c0001;
subgraph DFA136["DFA136 2 NFA States"]
NFA60_11_241("NFA60-11 char[1]")
NFA61_2_242[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_242 c0001;
end
class DFA136 c0001;
subgraph DFA137["DFA137 1 NFA States"]
NFA58_11_243("NFA58-11 char[1]")
end
subgraph DFA138["DFA138 1 NFA States"]
NFA56_11_244("NFA56-11 char[1]")
end
subgraph DFA139["DFA139 1 NFA States"]
NFA4_11_245[\"NFA4-11 char[1]
AcceptToken '#undef'"/]
class NFA4_11_245 c0001;
end
class DFA139 c0001;
subgraph DFA140["DFA140 1 NFA States"]
NFA1_11_246("NFA1-11 char[1]")
end
subgraph DFA141["DFA141 1 NFA States"]
NFA51_11_247("NFA51-11 char[1]")
end
subgraph DFA142["DFA142 1 NFA States"]
NFA50_11_248[\"NFA50-11 char[1]
AcceptToken '#ifdef'"/]
class NFA50_11_248 c0001;
end
class DFA142 c0001;
subgraph DFA143["DFA143 1 NFA States"]
NFA57_11_249("NFA57-11 char[1]")
end
subgraph DFA144["DFA144 1 NFA States"]
NFA55_11_250[\"NFA55-11 char[1]
AcceptToken '#error'"/]
class NFA55_11_250 c0001;
end
class DFA144 c0001;
subgraph DFA145["DFA145 1 NFA States"]
NFA54_11_251[\"NFA54-11 char[1]
AcceptToken '#endif'"/]
class NFA54_11_251 c0001;
end
class DFA145 c0001;
subgraph DFA146["DFA146 2 NFA States"]
NFA60_13_252[\"NFA60-13 char[1]
AcceptToken 'defined'"/]
class NFA60_13_252 c0001;
NFA61_2_253[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2_253 c0001;
end
class DFA146 c0001;
subgraph DFA147["DFA147 1 NFA States"]
NFA58_13_254("NFA58-13 char[1]")
end
subgraph DFA148["DFA148 1 NFA States"]
NFA56_13_255[\"NFA56-13 char[1]
AcceptToken '#pragma'"/]
class NFA56_13_255 c0001;
end
class DFA148 c0001;
subgraph DFA149["DFA149 1 NFA States"]
NFA1_13_256[\"NFA1-13 char[1]
AcceptToken '#define'"/]
class NFA1_13_256 c0001;
end
class DFA149 c0001;
subgraph DFA150["DFA150 1 NFA States"]
NFA51_13_257[\"NFA51-13 char[1]
AcceptToken '#ifndef'"/]
class NFA51_13_257 c0001;
end
class DFA150 c0001;
subgraph DFA151["DFA151 1 NFA States"]
NFA57_13_258("NFA57-13 char[1]")
end
subgraph DFA152["DFA152 1 NFA States"]
NFA58_15_259[\"NFA58-15 char[1]
AcceptToken '#version'"/]
class NFA58_15_259 c0001;
end
class DFA152 c0001;
subgraph DFA153["DFA153 1 NFA States"]
NFA57_15_260("NFA57-15 char[1]")
end
subgraph DFA154["DFA154 1 NFA States"]
NFA57_17_261("NFA57-17 char[1]")
end
subgraph DFA155["DFA155 1 NFA States"]
NFA57_19_262[\"NFA57-19 char[1]
AcceptToken '#extension'"/]
class NFA57_19_262 c0001;
end
class DFA155 c0001;
DFA0 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA0 -->|"}
BeginToken '}' 
ExtendToken '}' "|DFA2
DFA0 -->|"#92;{
BeginToken '{' 
ExtendToken '{' "|DFA3
DFA0 -->|":
BeginToken ':' 
ExtendToken ':' "|DFA4
DFA0 -->|"#92;?
BeginToken '?' 
ExtendToken '?' "|DFA5
DFA0 -->|"~
BeginToken '~' 
ExtendToken '~' "|DFA6
DFA0 -->|"#92;.
BeginToken '.' 
ExtendToken '.' "|DFA7
DFA0 -->|"]
BeginToken ']' 
ExtendToken ']' "|DFA8
DFA0 -->|"#92;[
BeginToken '[' 
ExtendToken '[' "|DFA9
DFA0 -->|";
BeginToken ';' 
ExtendToken ';' "|DFA10
DFA0 -->|",
BeginToken ',' 
ExtendToken ',' "|DFA11
DFA0 -->|"#92;)
BeginToken ')' 
ExtendToken ')' "|DFA12
DFA0 -->|"#92;(
BeginToken '(' 
ExtendToken '(' "|DFA13
DFA0 -->|"[A-Z]_[a-c]e[g-s][u-z]
BeginToken 'identifier' 'literalString' 
ExtendToken 'identifier' "|DFA14
DFA0 -->|"=
BeginToken '==' '=' 
ExtendToken '=' "|DFA15
DFA0 -->|"%
BeginToken '%' '%=' 
ExtendToken '%' "|DFA16
DFA0 -->|"#92;#42;
BeginToken '#42;' '#42;=' 
ExtendToken '#42;' "|DFA17
DFA0 -->|"!
BeginToken '!' '!=' 
ExtendToken '!' "|DFA18
DFA0 -->|"f
BeginToken 'identifier' 'literalString' 'boolConstant' 
ExtendToken 'identifier' "|DFA19
DFA0 -->|"t
BeginToken 'identifier' 'literalString' 'boolConstant' 
ExtendToken 'identifier' "|DFA20
DFA0 -->|"d
BeginToken 'defined' 'identifier' 'literalString' 
ExtendToken 'identifier' "|DFA21
DFA0 -->|"#92;|
BeginToken '|' '||' '|=' 
ExtendToken '|' "|DFA22
DFA0 -->|"^
BeginToken '^' '^^' '^=' 
ExtendToken '^' "|DFA23
DFA0 -->|"&
BeginToken '&' '&&' '&=' 
ExtendToken '&' "|DFA24
DFA0 -->|">
BeginToken '>>' '>' '>=' '>>=' 
ExtendToken '>' "|DFA25
DFA0 -->|"#92;<
BeginToken '<<' '<' '<=' '<<=' 
ExtendToken '<' "|DFA26
DFA0 -->|"#92;/
BeginToken '/' '/=' 'inlineComment' 
ExtendToken '/' "|DFA27
DFA0 -->|"[1-9]
BeginToken 'number' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA28
DFA0 -->|"0
BeginToken 'number' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA29
DFA0 -->|"-
BeginToken '--' '-' '-=' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken '-' "|DFA30
DFA0 -->|"#92;+
BeginToken '++' '+' '+=' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken '+' "|DFA31
DFA0 -->|"#35;
BeginToken '#35;define' '#35;undef' '#35;#35;' '#35;if' '#35;ifdef' '#35;ifndef' '#35;else' '#35;elif' '#35;endif' '#35;error' '#35;pragma' '#35;extension' '#35;version' '#35;line' "|DFA32
DFA1 -->|"#34;
ExtendToken 'literalString' "|DFA33
DFA1 -->|"[^#92;#92;#34;]"|DFA34
DFA1 -->|"#92;#92;"|DFA35
DFA14 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA14 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA15 -->|"=
ExtendToken '==' "|DFA37
DFA16 -->|"=
ExtendToken '%=' "|DFA38
DFA17 -->|"=
ExtendToken '#42;=' "|DFA39
DFA18 -->|"=
ExtendToken '!=' "|DFA40
DFA19 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA19 -->|"[0-9][A-Z]_[b-z]
ExtendToken 'identifier' "|DFA36
DFA19 -->|"a
ExtendToken 'identifier' "|DFA41
DFA20 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA20 -->|"[0-9][A-Z]_[a-q][s-z]
ExtendToken 'identifier' "|DFA36
DFA20 -->|"r
ExtendToken 'identifier' "|DFA42
DFA21 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA21 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA21 -->|"e
ExtendToken 'identifier' "|DFA43
DFA22 -->|"=
ExtendToken '|=' "|DFA44
DFA22 -->|"#92;|
ExtendToken '||' "|DFA45
DFA23 -->|"=
ExtendToken '^=' "|DFA46
DFA23 -->|"^
ExtendToken '^^' "|DFA47
DFA24 -->|"=
ExtendToken '&=' "|DFA48
DFA24 -->|"&
ExtendToken '&&' "|DFA49
DFA25 -->|"=
ExtendToken '>=' "|DFA50
DFA25 -->|">
ExtendToken '>>' "|DFA51
DFA26 -->|"=
ExtendToken '<=' "|DFA52
DFA26 -->|"#92;<
ExtendToken '<<' "|DFA53
DFA27 -->|"#92;/
ExtendToken 'inlineComment' "|DFA54
DFA27 -->|"=
ExtendToken '/=' "|DFA55
DFA28 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA28 -->|"[uU]
ExtendToken 'uintConstant' "|DFA57
DFA28 -->|"[Ee]"|DFA58
DFA28 -->|"[.]
ExtendToken 'doubleConstant' "|DFA59
DFA28 -->|"[0-9]
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA28
DFA29 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA29 -->|"[uU]
ExtendToken 'uintConstant' "|DFA57
DFA29 -->|"[Ee]"|DFA58
DFA29 -->|"x"|DFA60
DFA29 -->|"[.]
ExtendToken 'doubleConstant' "|DFA59
DFA29 -->|"[0-9]
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA28
DFA30 -->|"=
ExtendToken '-=' "|DFA61
DFA30 -->|"-
ExtendToken '--' "|DFA62
DFA30 -->|"[0-9]
BeginToken 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'intConstant' 'doubleConstant' "|DFA63
DFA31 -->|"=
ExtendToken '+=' "|DFA64
DFA31 -->|"#92;+
ExtendToken '++' "|DFA65
DFA31 -->|"[0-9]
BeginToken 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'intConstant' 'doubleConstant' "|DFA63
DFA32 -->|"l"|DFA66
DFA32 -->|"v"|DFA67
DFA32 -->|"p"|DFA68
DFA32 -->|"#35;
ExtendToken '#35;#35;' "|DFA69
DFA32 -->|"u"|DFA70
DFA32 -->|"d"|DFA71
DFA32 -->|"i"|DFA72
DFA32 -->|"e"|DFA73
DFA34 -->|"#34;
ExtendToken 'literalString' "|DFA33
DFA34 -->|"[^#92;#92;#34;]"|DFA34
DFA34 -->|"#92;#92;"|DFA35
DFA35 -->|"[#32;-~]"|DFA74
DFA36 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA41 -->|"[0-9][A-Z]_[a-k][m-z]
ExtendToken 'identifier' "|DFA36
DFA41 -->|"l
ExtendToken 'identifier' "|DFA75
DFA42 -->|"[0-9][A-Z]_[a-t][v-z]
ExtendToken 'identifier' "|DFA36
DFA42 -->|"u
ExtendToken 'identifier' "|DFA76
DFA43 -->|"[0-9][A-Z]_[a-e][g-z]
ExtendToken 'identifier' "|DFA36
DFA43 -->|"f
ExtendToken 'identifier' "|DFA77
DFA51 -->|"=
ExtendToken '>>=' "|DFA78
DFA53 -->|"=
ExtendToken '<<=' "|DFA79
DFA54 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment' "|DFA80
DFA58 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA81
DFA58 -->|"[-+]"|DFA82
DFA59 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA59 -->|"[Ee]"|DFA58
DFA59 -->|"[.]
ExtendToken 'doubleConstant' "|DFA83
DFA59 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA84
DFA60 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant' "|DFA85
DFA63 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA63 -->|"[uU]
ExtendToken 'uintConstant' "|DFA57
DFA63 -->|"[Ee]"|DFA58
DFA63 -->|"[.]
ExtendToken 'doubleConstant' "|DFA86
DFA63 -->|"[0-9]
ExtendToken 'intConstant' 'doubleConstant' "|DFA63
DFA66 -->|"i"|DFA87
DFA67 -->|"e"|DFA88
DFA68 -->|"r"|DFA89
DFA70 -->|"n"|DFA90
DFA71 -->|"e"|DFA91
DFA72 -->|"f
ExtendToken '#35;if' "|DFA92
DFA73 -->|"x"|DFA93
DFA73 -->|"r"|DFA94
DFA73 -->|"n"|DFA95
DFA73 -->|"l"|DFA96
DFA74 -->|"#34;
ExtendToken 'literalString' "|DFA33
DFA74 -->|"[^#92;#92;#34;]"|DFA34
DFA74 -->|"#92;#92;"|DFA35
DFA75 -->|"[0-9][A-Z]_[a-r][t-z]
ExtendToken 'identifier' "|DFA36
DFA75 -->|"s
ExtendToken 'identifier' "|DFA97
DFA76 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA76 -->|"e
ExtendToken 'identifier' 'boolConstant' "|DFA98
DFA77 -->|"[0-9][A-Z]_[a-h][j-z]
ExtendToken 'identifier' "|DFA36
DFA77 -->|"i
ExtendToken 'identifier' "|DFA99
DFA80 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment' "|DFA80
DFA81 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA81 -->|"[Ee]"|DFA100
DFA81 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA81
DFA82 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA81
DFA83 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA83 -->|"[Ee]"|DFA58
DFA83 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA101
DFA84 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA84 -->|"[Ee]"|DFA58
DFA84 -->|"[.]
ExtendToken 'doubleConstant' "|DFA102
DFA84 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA84
DFA85 -->|"[uU]
ExtendToken 'uintConstant' "|DFA103
DFA85 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant' "|DFA85
DFA86 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA86 -->|"[Ee]"|DFA58
DFA86 -->|"[.]
ExtendToken 'doubleConstant' "|DFA83
DFA86 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA104
DFA87 -->|"n"|DFA105
DFA88 -->|"r"|DFA106
DFA89 -->|"a"|DFA107
DFA90 -->|"d"|DFA108
DFA91 -->|"f"|DFA109
DFA92 -->|"n"|DFA110
DFA92 -->|"d"|DFA111
DFA93 -->|"t"|DFA112
DFA94 -->|"r"|DFA113
DFA95 -->|"d"|DFA114
DFA96 -->|"i"|DFA115
DFA96 -->|"s"|DFA116
DFA97 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA97 -->|"e
ExtendToken 'identifier' 'boolConstant' "|DFA117
DFA98 -->|"[^a-zA-Z0-9_]"|DFA118
DFA98 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA99 -->|"[0-9][A-Z]_[a-m][o-z]
ExtendToken 'identifier' "|DFA36
DFA99 -->|"n
ExtendToken 'identifier' "|DFA119
DFA100 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA120
DFA100 -->|"[-+]"|DFA121
DFA101 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA101 -->|"[Ee]"|DFA58
DFA101 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA101
DFA102 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA102 -->|"[Ee]"|DFA58
DFA102 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA122
DFA104 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA104 -->|"[Ee]"|DFA58
DFA104 -->|"[.]
ExtendToken 'doubleConstant' "|DFA83
DFA104 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA104
DFA105 -->|"e
ExtendToken '#35;line' "|DFA123
DFA106 -->|"s"|DFA124
DFA107 -->|"g"|DFA125
DFA108 -->|"e"|DFA126
DFA109 -->|"i"|DFA127
DFA110 -->|"d"|DFA128
DFA111 -->|"e"|DFA129
DFA112 -->|"e"|DFA130
DFA113 -->|"o"|DFA131
DFA114 -->|"i"|DFA132
DFA115 -->|"f
ExtendToken '#35;elif' "|DFA133
DFA116 -->|"e
ExtendToken '#35;else' "|DFA134
DFA117 -->|"[^a-zA-Z0-9_]"|DFA135
DFA117 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA119 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA119 -->|"e
ExtendToken 'identifier' "|DFA136
DFA120 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA120 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA120
DFA121 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA120
DFA122 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA122 -->|"[Ee]"|DFA58
DFA122 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA122
DFA124 -->|"i"|DFA137
DFA125 -->|"m"|DFA138
DFA126 -->|"f
ExtendToken '#35;undef' "|DFA139
DFA127 -->|"n"|DFA140
DFA128 -->|"e"|DFA141
DFA129 -->|"f
ExtendToken '#35;ifdef' "|DFA142
DFA130 -->|"n"|DFA143
DFA131 -->|"r
ExtendToken '#35;error' "|DFA144
DFA132 -->|"f
ExtendToken '#35;endif' "|DFA145
DFA136 -->|"[0-9][A-Z]_[a-c][e-z]
ExtendToken 'identifier' "|DFA36
DFA136 -->|"d
ExtendToken 'defined' 'identifier' "|DFA146
DFA137 -->|"o"|DFA147
DFA138 -->|"a
ExtendToken '#35;pragma' "|DFA148
DFA140 -->|"e
ExtendToken '#35;define' "|DFA149
DFA141 -->|"f
ExtendToken '#35;ifndef' "|DFA150
DFA143 -->|"s"|DFA151
DFA146 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA147 -->|"n
ExtendToken '#35;version' "|DFA152
DFA151 -->|"i"|DFA153
DFA153 -->|"o"|DFA154
DFA154 -->|"n
ExtendToken '#35;extension' "|DFA155
