flowchart
classDef c0001 color:#FF0000;
classDef c0010 stroke-dasharray: 10 10;
classDef c0011 stroke-dasharray: 10 10,color:#FF0000;
classDef c0100 fill:#BB66EE;
classDef c0101 fill:#BB66EE,color:#FF0000;
classDef c0110 fill:#BB66EE,stroke-dasharray: 10 10;
classDef c0111 fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
classDef c1000 stroke:#333,stroke-width:4px;
classDef c1001 stroke:#333,stroke-width:4px,color:#FF0000;
classDef c1010 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10;
classDef c1011 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10,color:#FF0000;
classDef c1100 stroke:#333,stroke-width:4px,fill:#BB66EE;
classDef c1101 stroke:#333,stroke-width:4px,fill:#BB66EE,color:#FF0000;
classDef c1110 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10;
classDef c1111 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
DFA0{{"DFA0 wholeStart"}}
class DFA0 c1000;
DFA1{{"DFA1 1 NFA States"}}
DFA2[\"DFA2 1 NFA States
AcceptToken '}'"/]
class DFA2 c0001;
DFA3[\"DFA3 1 NFA States
AcceptToken '{'"/]
class DFA3 c0001;
DFA4[\"DFA4 1 NFA States
AcceptToken ':'"/]
class DFA4 c0001;
DFA5[\"DFA5 1 NFA States
AcceptToken '?'"/]
class DFA5 c0001;
DFA6[\"DFA6 1 NFA States
AcceptToken '~'"/]
class DFA6 c0001;
DFA7[\"DFA7 1 NFA States
AcceptToken '.'"/]
class DFA7 c0001;
DFA8[\"DFA8 1 NFA States
AcceptToken ']'"/]
class DFA8 c0001;
DFA9[\"DFA9 1 NFA States
AcceptToken '['"/]
class DFA9 c0001;
DFA10[\"DFA10 1 NFA States
AcceptToken ';'"/]
class DFA10 c0001;
DFA11[\"DFA11 1 NFA States
AcceptToken ','"/]
class DFA11 c0001;
DFA12[\"DFA12 1 NFA States
AcceptToken ')'"/]
class DFA12 c0001;
DFA13[\"DFA13 1 NFA States
AcceptToken '('"/]
class DFA13 c0001;
DFA14[\"DFA14 2 NFA States
AcceptToken 'identifier'"/]
class DFA14 c1001;
DFA15[\"DFA15 2 NFA States
AcceptToken '='"/]
class DFA15 c0001;
DFA16[\"DFA16 2 NFA States
AcceptToken '%'"/]
class DFA16 c0001;
DFA17[\"DFA17 2 NFA States
AcceptToken '*'"/]
class DFA17 c0001;
DFA18[\"DFA18 2 NFA States
AcceptToken '!'"/]
class DFA18 c0001;
DFA19[\"DFA19 3 NFA States
AcceptToken 'identifier'"/]
class DFA19 c1001;
DFA20[\"DFA20 3 NFA States
AcceptToken 'identifier'"/]
class DFA20 c1001;
DFA21[\"DFA21 3 NFA States
AcceptToken 'identifier'"/]
class DFA21 c1001;
DFA22[\"DFA22 3 NFA States
AcceptToken '|'"/]
class DFA22 c0001;
DFA23[\"DFA23 3 NFA States
AcceptToken '^'"/]
class DFA23 c0001;
DFA24[\"DFA24 3 NFA States
AcceptToken '&'"/]
class DFA24 c0001;
DFA25[\"DFA25 4 NFA States
AcceptToken '>'"/]
class DFA25 c0001;
DFA26[\"DFA26 4 NFA States
AcceptToken '<'"/]
class DFA26 c0001;
DFA27[\"DFA27 3 NFA States
AcceptToken '/'"/]
class DFA27 c0001;
DFA28[\"DFA28 5 NFA States
AcceptToken 'number'
AcceptToken 'intConstant'
AcceptToken 'doubleConstant'"/]
class DFA28 c0001;
DFA29[\"DFA29 7 NFA States
AcceptToken 'number'
AcceptToken 'intConstant'
AcceptToken 'doubleConstant'"/]
class DFA29 c0001;
DFA30[\"DFA30 7 NFA States
AcceptToken '-'"/]
class DFA30 c1001;
DFA31[\"DFA31 7 NFA States
AcceptToken '+'"/]
class DFA31 c1001;
DFA32{{"DFA32 14 NFA States"}}
DFA33[\"DFA33 1 NFA States
AcceptToken 'literalString'"/]
class DFA33 c0001;
DFA34{{"DFA34 1 NFA States"}}
DFA35{{"DFA35 1 NFA States"}}
DFA36[\"DFA36 1 NFA States
AcceptToken 'identifier'"/]
class DFA36 c0001;
DFA37[\"DFA37 1 NFA States
AcceptToken '=='"/]
class DFA37 c0001;
DFA38[\"DFA38 1 NFA States
AcceptToken '%='"/]
class DFA38 c0001;
DFA39[\"DFA39 1 NFA States
AcceptToken '*='"/]
class DFA39 c0001;
DFA40[\"DFA40 1 NFA States
AcceptToken '!='"/]
class DFA40 c0001;
DFA41[\"DFA41 2 NFA States
AcceptToken 'identifier'"/]
class DFA41 c0001;
DFA42[\"DFA42 2 NFA States
AcceptToken 'identifier'"/]
class DFA42 c0001;
DFA43[\"DFA43 2 NFA States
AcceptToken 'identifier'"/]
class DFA43 c0001;
DFA44[\"DFA44 1 NFA States
AcceptToken '|='"/]
class DFA44 c0001;
DFA45[\"DFA45 1 NFA States
AcceptToken '||'"/]
class DFA45 c0001;
DFA46[\"DFA46 1 NFA States
AcceptToken '^='"/]
class DFA46 c0001;
DFA47[\"DFA47 1 NFA States
AcceptToken '^^'"/]
class DFA47 c0001;
DFA48[\"DFA48 1 NFA States
AcceptToken '&='"/]
class DFA48 c0001;
DFA49[\"DFA49 1 NFA States
AcceptToken '&&'"/]
class DFA49 c0001;
DFA50[\"DFA50 1 NFA States
AcceptToken '>='"/]
class DFA50 c0001;
DFA51[\"DFA51 2 NFA States
AcceptToken '>>'"/]
class DFA51 c0001;
DFA52[\"DFA52 1 NFA States
AcceptToken '<='"/]
class DFA52 c0001;
DFA53[\"DFA53 2 NFA States
AcceptToken '<<'"/]
class DFA53 c0001;
DFA54[\"DFA54 1 NFA States
AcceptToken 'inlineComment'"/]
class DFA54 c0001;
DFA55[\"DFA55 1 NFA States
AcceptToken '/='"/]
class DFA55 c0001;
DFA56[\"DFA56 1 NFA States
AcceptToken 'floatConstant'"/]
class DFA56 c0001;
DFA57[\"DFA57 1 NFA States
AcceptToken 'uintConstant'"/]
class DFA57 c0001;
DFA58{{"DFA58 2 NFA States"}}
DFA59[\"DFA59 3 NFA States
AcceptToken 'doubleConstant'"/]
class DFA59 c0001;
DFA60{{"DFA60 2 NFA States"}}
DFA61[\"DFA61 1 NFA States
AcceptToken '-='"/]
class DFA61 c0001;
DFA62[\"DFA62 1 NFA States
AcceptToken '--'"/]
class DFA62 c0001;
DFA63[\"DFA63 4 NFA States
AcceptToken 'intConstant'
AcceptToken 'doubleConstant'"/]
class DFA63 c0001;
DFA64[\"DFA64 1 NFA States
AcceptToken '+='"/]
class DFA64 c0001;
DFA65[\"DFA65 1 NFA States
AcceptToken '++'"/]
class DFA65 c0001;
DFA66{{"DFA66 1 NFA States"}}
DFA67{{"DFA67 1 NFA States"}}
DFA68{{"DFA68 1 NFA States"}}
DFA69[\"DFA69 1 NFA States
AcceptToken '##'"/]
class DFA69 c0001;
DFA70{{"DFA70 1 NFA States"}}
DFA71{{"DFA71 1 NFA States"}}
DFA72{{"DFA72 3 NFA States"}}
DFA73{{"DFA73 5 NFA States"}}
DFA74{{"DFA74 1 NFA States"}}
DFA75[\"DFA75 2 NFA States
AcceptToken 'identifier'"/]
class DFA75 c0001;
DFA76[\"DFA76 2 NFA States
AcceptToken 'identifier'"/]
class DFA76 c0001;
DFA77[\"DFA77 2 NFA States
AcceptToken 'identifier'"/]
class DFA77 c0001;
DFA78[\"DFA78 1 NFA States
AcceptToken '>>='"/]
class DFA78 c0001;
DFA79[\"DFA79 1 NFA States
AcceptToken '<<='"/]
class DFA79 c0001;
DFA80[\"DFA80 1 NFA States
AcceptToken 'inlineComment'"/]
class DFA80 c0001;
DFA81[\"DFA81 2 NFA States
AcceptToken 'doubleConstant'"/]
class DFA81 c0001;
DFA82{{"DFA82 2 NFA States"}}
DFA83[\"DFA83 2 NFA States
AcceptToken 'doubleConstant'"/]
class DFA83 c0001;
DFA84[\"DFA84 3 NFA States
AcceptToken 'number'
AcceptToken 'doubleConstant'"/]
class DFA84 c0001;
DFA85[\"DFA85 2 NFA States
AcceptToken 'intConstant'"/]
class DFA85 c0001;
DFA86[\"DFA86 2 NFA States
AcceptToken 'doubleConstant'"/]
class DFA86 c0001;
DFA87{{"DFA87 1 NFA States"}}
DFA88{{"DFA88 1 NFA States"}}
DFA89{{"DFA89 1 NFA States"}}
DFA90{{"DFA90 1 NFA States"}}
DFA91{{"DFA91 1 NFA States"}}
DFA92[\"DFA92 3 NFA States
AcceptToken '#if'"/]
class DFA92 c0001;
DFA93{{"DFA93 1 NFA States"}}
DFA94{{"DFA94 1 NFA States"}}
DFA95{{"DFA95 1 NFA States"}}
DFA96{{"DFA96 2 NFA States"}}
DFA97[\"DFA97 2 NFA States
AcceptToken 'identifier'"/]
class DFA97 c0001;
DFA98[\"DFA98 2 NFA States
AcceptToken 'identifier'"/]
class DFA98 c0001;
DFA99[\"DFA99 2 NFA States
AcceptToken 'identifier'"/]
class DFA99 c0001;
DFA100{{"DFA100 2 NFA States"}}
DFA101[\"DFA101 2 NFA States
AcceptToken 'doubleConstant'"/]
class DFA101 c0001;
DFA102[\"DFA102 3 NFA States
AcceptToken 'doubleConstant'"/]
class DFA102 c0001;
DFA103[\"DFA103 1 NFA States
AcceptToken 'uintConstant'"/]
class DFA103 c0001;
DFA104[\"DFA104 2 NFA States
AcceptToken 'doubleConstant'"/]
class DFA104 c0001;
DFA105{{"DFA105 1 NFA States"}}
DFA106{{"DFA106 1 NFA States"}}
DFA107{{"DFA107 1 NFA States"}}
DFA108{{"DFA108 1 NFA States"}}
DFA109{{"DFA109 1 NFA States"}}
DFA110{{"DFA110 1 NFA States"}}
DFA111{{"DFA111 1 NFA States"}}
DFA112{{"DFA112 1 NFA States"}}
DFA113{{"DFA113 1 NFA States"}}
DFA114{{"DFA114 1 NFA States"}}
DFA115{{"DFA115 1 NFA States"}}
DFA116{{"DFA116 1 NFA States"}}
DFA117[\"DFA117 2 NFA States
AcceptToken 'identifier'"/]
class DFA117 c0001;
DFA118[\"DFA118 1 NFA States
AcceptToken 'boolConstant'"/]
class DFA118 c0001;
DFA119[\"DFA119 2 NFA States
AcceptToken 'identifier'"/]
class DFA119 c0001;
DFA120[\"DFA120 2 NFA States
AcceptToken 'doubleConstant'"/]
class DFA120 c0001;
DFA121{{"DFA121 2 NFA States"}}
DFA122[\"DFA122 3 NFA States
AcceptToken 'number'
AcceptToken 'doubleConstant'"/]
class DFA122 c0001;
DFA123[\"DFA123 1 NFA States
AcceptToken '#line'"/]
class DFA123 c0001;
DFA124{{"DFA124 1 NFA States"}}
DFA125{{"DFA125 1 NFA States"}}
DFA126{{"DFA126 1 NFA States"}}
DFA127{{"DFA127 1 NFA States"}}
DFA128{{"DFA128 1 NFA States"}}
DFA129{{"DFA129 1 NFA States"}}
DFA130{{"DFA130 1 NFA States"}}
DFA131{{"DFA131 1 NFA States"}}
DFA132{{"DFA132 1 NFA States"}}
DFA133[\"DFA133 1 NFA States
AcceptToken '#elif'"/]
class DFA133 c0001;
DFA134[\"DFA134 1 NFA States
AcceptToken '#else'"/]
class DFA134 c0001;
DFA135[\"DFA135 1 NFA States
AcceptToken 'boolConstant'"/]
class DFA135 c0001;
DFA136[\"DFA136 2 NFA States
AcceptToken 'identifier'"/]
class DFA136 c0001;
DFA137{{"DFA137 1 NFA States"}}
DFA138{{"DFA138 1 NFA States"}}
DFA139[\"DFA139 1 NFA States
AcceptToken '#undef'"/]
class DFA139 c0001;
DFA140{{"DFA140 1 NFA States"}}
DFA141{{"DFA141 1 NFA States"}}
DFA142[\"DFA142 1 NFA States
AcceptToken '#ifdef'"/]
class DFA142 c0001;
DFA143{{"DFA143 1 NFA States"}}
DFA144[\"DFA144 1 NFA States
AcceptToken '#error'"/]
class DFA144 c0001;
DFA145[\"DFA145 1 NFA States
AcceptToken '#endif'"/]
class DFA145 c0001;
DFA146[\"DFA146 2 NFA States
AcceptToken 'defined'
AcceptToken 'identifier'"/]
class DFA146 c0001;
DFA147{{"DFA147 1 NFA States"}}
DFA148[\"DFA148 1 NFA States
AcceptToken '#pragma'"/]
class DFA148 c0001;
DFA149[\"DFA149 1 NFA States
AcceptToken '#define'"/]
class DFA149 c0001;
DFA150[\"DFA150 1 NFA States
AcceptToken '#ifndef'"/]
class DFA150 c0001;
DFA151{{"DFA151 1 NFA States"}}
DFA152[\"DFA152 1 NFA States
AcceptToken '#version'"/]
class DFA152 c0001;
DFA153{{"DFA153 1 NFA States"}}
DFA154{{"DFA154 1 NFA States"}}
DFA155[\"DFA155 1 NFA States
AcceptToken '#extension'"/]
class DFA155 c0001;
DFA0 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA0 -->|"}
BeginToken '}' 
ExtendToken '}' "|DFA2
DFA0 -->|"#92;{
BeginToken '{' 
ExtendToken '{' "|DFA3
DFA0 -->|":
BeginToken ':' 
ExtendToken ':' "|DFA4
DFA0 -->|"#92;?
BeginToken '?' 
ExtendToken '?' "|DFA5
DFA0 -->|"~
BeginToken '~' 
ExtendToken '~' "|DFA6
DFA0 -->|"#92;.
BeginToken '.' 
ExtendToken '.' "|DFA7
DFA0 -->|"]
BeginToken ']' 
ExtendToken ']' "|DFA8
DFA0 -->|"#92;[
BeginToken '[' 
ExtendToken '[' "|DFA9
DFA0 -->|";
BeginToken ';' 
ExtendToken ';' "|DFA10
DFA0 -->|",
BeginToken ',' 
ExtendToken ',' "|DFA11
DFA0 -->|"#92;)
BeginToken ')' 
ExtendToken ')' "|DFA12
DFA0 -->|"#92;(
BeginToken '(' 
ExtendToken '(' "|DFA13
DFA0 -->|"[A-Z]_[a-c]e[g-s][u-z]
BeginToken 'identifier' 'literalString' 
ExtendToken 'identifier' "|DFA14
DFA0 -->|"=
BeginToken '==' '=' 
ExtendToken '=' "|DFA15
DFA0 -->|"%
BeginToken '%' '%=' 
ExtendToken '%' "|DFA16
DFA0 -->|"#92;#42;
BeginToken '#42;' '#42;=' 
ExtendToken '#42;' "|DFA17
DFA0 -->|"!
BeginToken '!' '!=' 
ExtendToken '!' "|DFA18
DFA0 -->|"f
BeginToken 'identifier' 'literalString' 'boolConstant' 
ExtendToken 'identifier' "|DFA19
DFA0 -->|"t
BeginToken 'identifier' 'literalString' 'boolConstant' 
ExtendToken 'identifier' "|DFA20
DFA0 -->|"d
BeginToken 'defined' 'identifier' 'literalString' 
ExtendToken 'identifier' "|DFA21
DFA0 -->|"#92;|
BeginToken '|' '||' '|=' 
ExtendToken '|' "|DFA22
DFA0 -->|"^
BeginToken '^' '^^' '^=' 
ExtendToken '^' "|DFA23
DFA0 -->|"&
BeginToken '&' '&&' '&=' 
ExtendToken '&' "|DFA24
DFA0 -->|">
BeginToken '>>' '>' '>=' '>>=' 
ExtendToken '>' "|DFA25
DFA0 -->|"#92;<
BeginToken '<<' '<' '<=' '<<=' 
ExtendToken '<' "|DFA26
DFA0 -->|"#92;/
BeginToken '/' '/=' 'inlineComment' 
ExtendToken '/' "|DFA27
DFA0 -->|"[1-9]
BeginToken 'number' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA28
DFA0 -->|"0
BeginToken 'number' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA29
DFA0 -->|"-
BeginToken '--' '-' '-=' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken '-' "|DFA30
DFA0 -->|"#92;+
BeginToken '++' '+' '+=' 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken '+' "|DFA31
DFA0 -->|"#35;
BeginToken '#35;define' '#35;undef' '#35;#35;' '#35;if' '#35;ifdef' '#35;ifndef' '#35;else' '#35;elif' '#35;endif' '#35;error' '#35;pragma' '#35;extension' '#35;version' '#35;line' "|DFA32
DFA1 -->|"#34;
ExtendToken 'literalString' "|DFA33
DFA1 -->|"[^#92;#92;#34;]"|DFA34
DFA1 -->|"#92;#92;"|DFA35
DFA14 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA14 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA15 -->|"=
ExtendToken '==' "|DFA37
DFA16 -->|"=
ExtendToken '%=' "|DFA38
DFA17 -->|"=
ExtendToken '#42;=' "|DFA39
DFA18 -->|"=
ExtendToken '!=' "|DFA40
DFA19 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA19 -->|"[0-9][A-Z]_[b-z]
ExtendToken 'identifier' "|DFA36
DFA19 -->|"a
ExtendToken 'identifier' "|DFA41
DFA20 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA20 -->|"[0-9][A-Z]_[a-q][s-z]
ExtendToken 'identifier' "|DFA36
DFA20 -->|"r
ExtendToken 'identifier' "|DFA42
DFA21 -->|"#34;
BeginToken 'literalString' "|DFA1
DFA21 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA21 -->|"e
ExtendToken 'identifier' "|DFA43
DFA22 -->|"=
ExtendToken '|=' "|DFA44
DFA22 -->|"#92;|
ExtendToken '||' "|DFA45
DFA23 -->|"=
ExtendToken '^=' "|DFA46
DFA23 -->|"^
ExtendToken '^^' "|DFA47
DFA24 -->|"=
ExtendToken '&=' "|DFA48
DFA24 -->|"&
ExtendToken '&&' "|DFA49
DFA25 -->|"=
ExtendToken '>=' "|DFA50
DFA25 -->|">
ExtendToken '>>' "|DFA51
DFA26 -->|"=
ExtendToken '<=' "|DFA52
DFA26 -->|"#92;<
ExtendToken '<<' "|DFA53
DFA27 -->|"#92;/
ExtendToken 'inlineComment' "|DFA54
DFA27 -->|"=
ExtendToken '/=' "|DFA55
DFA28 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA28 -->|"[uU]
ExtendToken 'uintConstant' "|DFA57
DFA28 -->|"[Ee]"|DFA58
DFA28 -->|"[.]
ExtendToken 'doubleConstant' "|DFA59
DFA28 -->|"[0-9]
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA28
DFA29 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA29 -->|"[uU]
ExtendToken 'uintConstant' "|DFA57
DFA29 -->|"[Ee]"|DFA58
DFA29 -->|"x"|DFA60
DFA29 -->|"[.]
ExtendToken 'doubleConstant' "|DFA59
DFA29 -->|"[0-9]
ExtendToken 'number' 'intConstant' 'doubleConstant' "|DFA28
DFA30 -->|"=
ExtendToken '-=' "|DFA61
DFA30 -->|"-
ExtendToken '--' "|DFA62
DFA30 -->|"[0-9]
BeginToken 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'intConstant' 'doubleConstant' "|DFA63
DFA31 -->|"=
ExtendToken '+=' "|DFA64
DFA31 -->|"#92;+
ExtendToken '++' "|DFA65
DFA31 -->|"[0-9]
BeginToken 'intConstant' 'uintConstant' 'floatConstant' 'doubleConstant' 
ExtendToken 'intConstant' 'doubleConstant' "|DFA63
DFA32 -->|"l"|DFA66
DFA32 -->|"v"|DFA67
DFA32 -->|"p"|DFA68
DFA32 -->|"#35;
ExtendToken '#35;#35;' "|DFA69
DFA32 -->|"u"|DFA70
DFA32 -->|"d"|DFA71
DFA32 -->|"i"|DFA72
DFA32 -->|"e"|DFA73
DFA34 -->|"#34;
ExtendToken 'literalString' "|DFA33
DFA34 -->|"[^#92;#92;#34;]"|DFA34
DFA34 -->|"#92;#92;"|DFA35
DFA35 -->|"[#32;-~]"|DFA74
DFA36 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA41 -->|"[0-9][A-Z]_[a-k][m-z]
ExtendToken 'identifier' "|DFA36
DFA41 -->|"l
ExtendToken 'identifier' "|DFA75
DFA42 -->|"[0-9][A-Z]_[a-t][v-z]
ExtendToken 'identifier' "|DFA36
DFA42 -->|"u
ExtendToken 'identifier' "|DFA76
DFA43 -->|"[0-9][A-Z]_[a-e][g-z]
ExtendToken 'identifier' "|DFA36
DFA43 -->|"f
ExtendToken 'identifier' "|DFA77
DFA51 -->|"=
ExtendToken '>>=' "|DFA78
DFA53 -->|"=
ExtendToken '<<=' "|DFA79
DFA54 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment' "|DFA80
DFA58 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA81
DFA58 -->|"[-+]"|DFA82
DFA59 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA59 -->|"[Ee]"|DFA58
DFA59 -->|"[.]
ExtendToken 'doubleConstant' "|DFA83
DFA59 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA84
DFA60 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant' "|DFA85
DFA63 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA63 -->|"[uU]
ExtendToken 'uintConstant' "|DFA57
DFA63 -->|"[Ee]"|DFA58
DFA63 -->|"[.]
ExtendToken 'doubleConstant' "|DFA86
DFA63 -->|"[0-9]
ExtendToken 'intConstant' 'doubleConstant' "|DFA63
DFA66 -->|"i"|DFA87
DFA67 -->|"e"|DFA88
DFA68 -->|"r"|DFA89
DFA70 -->|"n"|DFA90
DFA71 -->|"e"|DFA91
DFA72 -->|"f
ExtendToken '#35;if' "|DFA92
DFA73 -->|"x"|DFA93
DFA73 -->|"r"|DFA94
DFA73 -->|"n"|DFA95
DFA73 -->|"l"|DFA96
DFA74 -->|"#34;
ExtendToken 'literalString' "|DFA33
DFA74 -->|"[^#92;#92;#34;]"|DFA34
DFA74 -->|"#92;#92;"|DFA35
DFA75 -->|"[0-9][A-Z]_[a-r][t-z]
ExtendToken 'identifier' "|DFA36
DFA75 -->|"s
ExtendToken 'identifier' "|DFA97
DFA76 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA76 -->|"e
ExtendToken 'identifier' 'boolConstant' "|DFA98
DFA77 -->|"[0-9][A-Z]_[a-h][j-z]
ExtendToken 'identifier' "|DFA36
DFA77 -->|"i
ExtendToken 'identifier' "|DFA99
DFA80 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment' "|DFA80
DFA81 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA81 -->|"[Ee]"|DFA100
DFA81 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA81
DFA82 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA81
DFA83 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA83 -->|"[Ee]"|DFA58
DFA83 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA101
DFA84 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA84 -->|"[Ee]"|DFA58
DFA84 -->|"[.]
ExtendToken 'doubleConstant' "|DFA102
DFA84 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA84
DFA85 -->|"[uU]
ExtendToken 'uintConstant' "|DFA103
DFA85 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant' "|DFA85
DFA86 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA86 -->|"[Ee]"|DFA58
DFA86 -->|"[.]
ExtendToken 'doubleConstant' "|DFA83
DFA86 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA104
DFA87 -->|"n"|DFA105
DFA88 -->|"r"|DFA106
DFA89 -->|"a"|DFA107
DFA90 -->|"d"|DFA108
DFA91 -->|"f"|DFA109
DFA92 -->|"n"|DFA110
DFA92 -->|"d"|DFA111
DFA93 -->|"t"|DFA112
DFA94 -->|"r"|DFA113
DFA95 -->|"d"|DFA114
DFA96 -->|"i"|DFA115
DFA96 -->|"s"|DFA116
DFA97 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA97 -->|"e
ExtendToken 'identifier' 'boolConstant' "|DFA117
DFA98 -->|"[^a-zA-Z0-9_]"|DFA118
DFA98 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA99 -->|"[0-9][A-Z]_[a-m][o-z]
ExtendToken 'identifier' "|DFA36
DFA99 -->|"n
ExtendToken 'identifier' "|DFA119
DFA100 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA120
DFA100 -->|"[-+]"|DFA121
DFA101 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA101 -->|"[Ee]"|DFA58
DFA101 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA101
DFA102 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA102 -->|"[Ee]"|DFA58
DFA102 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA122
DFA104 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA104 -->|"[Ee]"|DFA58
DFA104 -->|"[.]
ExtendToken 'doubleConstant' "|DFA83
DFA104 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA104
DFA105 -->|"e
ExtendToken '#35;line' "|DFA123
DFA106 -->|"s"|DFA124
DFA107 -->|"g"|DFA125
DFA108 -->|"e"|DFA126
DFA109 -->|"i"|DFA127
DFA110 -->|"d"|DFA128
DFA111 -->|"e"|DFA129
DFA112 -->|"e"|DFA130
DFA113 -->|"o"|DFA131
DFA114 -->|"i"|DFA132
DFA115 -->|"f
ExtendToken '#35;elif' "|DFA133
DFA116 -->|"e
ExtendToken '#35;else' "|DFA134
DFA117 -->|"[^a-zA-Z0-9_]"|DFA135
DFA117 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA119 -->|"[0-9][A-Z]_[a-d][f-z]
ExtendToken 'identifier' "|DFA36
DFA119 -->|"e
ExtendToken 'identifier' "|DFA136
DFA120 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA120 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA120
DFA121 -->|"[0-9]
ExtendToken 'doubleConstant' "|DFA120
DFA122 -->|"[fF]
ExtendToken 'floatConstant' "|DFA56
DFA122 -->|"[Ee]"|DFA58
DFA122 -->|"[0-9]
ExtendToken 'number' 'doubleConstant' "|DFA122
DFA124 -->|"i"|DFA137
DFA125 -->|"m"|DFA138
DFA126 -->|"f
ExtendToken '#35;undef' "|DFA139
DFA127 -->|"n"|DFA140
DFA128 -->|"e"|DFA141
DFA129 -->|"f
ExtendToken '#35;ifdef' "|DFA142
DFA130 -->|"n"|DFA143
DFA131 -->|"r
ExtendToken '#35;error' "|DFA144
DFA132 -->|"f
ExtendToken '#35;endif' "|DFA145
DFA136 -->|"[0-9][A-Z]_[a-c][e-z]
ExtendToken 'identifier' "|DFA36
DFA136 -->|"d
ExtendToken 'defined' 'identifier' "|DFA146
DFA137 -->|"o"|DFA147
DFA138 -->|"a
ExtendToken '#35;pragma' "|DFA148
DFA140 -->|"e
ExtendToken '#35;define' "|DFA149
DFA141 -->|"f
ExtendToken '#35;ifndef' "|DFA150
DFA143 -->|"s"|DFA151
DFA146 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier' "|DFA36
DFA147 -->|"n
ExtendToken '#35;version' "|DFA152
DFA151 -->|"i"|DFA153
DFA153 -->|"o"|DFA154
DFA154 -->|"n
ExtendToken '#35;extension' "|DFA155
