flowchart
classDef c0001 color:#FF0000;
classDef c0010 stroke-dasharray: 10 10;
classDef c0011 stroke-dasharray: 10 10,color:#FF0000;
classDef c0100 fill:#BB66EE;
classDef c0101 fill:#BB66EE,color:#FF0000;
classDef c0110 fill:#BB66EE,stroke-dasharray: 10 10;
classDef c0111 fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
classDef c1000 stroke:#333,stroke-width:4px;
classDef c1001 stroke:#333,stroke-width:4px,color:#FF0000;
classDef c1010 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10;
classDef c1011 stroke:#333,stroke-width:4px,stroke-dasharray: 10 10,color:#FF0000;
classDef c1100 stroke:#333,stroke-width:4px,fill:#BB66EE;
classDef c1101 stroke:#333,stroke-width:4px,fill:#BB66EE,color:#FF0000;
classDef c1110 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10;
classDef c1111 stroke:#333,stroke-width:4px,fill:#BB66EE,stroke-dasharray: 10 10,color:#FF0000;
NFA0_0("NFA0-0 wholeStart")
class NFA0_0 c1000;
NFA1_1("NFA1-1 char[1]")
NFA2_1[\"NFA2-1 char[1]
AcceptToken '('"/]
class NFA2_1 c0001;
NFA3_1[\"NFA3-1 char[1]
AcceptToken ')'"/]
class NFA3_1 c0001;
NFA4_1("NFA4-1 char[1]")
NFA5_1[\"NFA5-1 char[1]
AcceptToken ','"/]
class NFA5_1 c0001;
NFA6_1[\"NFA6-1 char[1]
AcceptToken ';'"/]
class NFA6_1 c0001;
NFA7_1[\"NFA7-1 char[1]
AcceptToken '['"/]
class NFA7_1 c0001;
NFA8_1[\"NFA8-1 char[1]
AcceptToken ']'"/]
class NFA8_1 c0001;
NFA9_1[\"NFA9-1 char[1]
AcceptToken '.'"/]
class NFA9_1 c0001;
NFA10_1("NFA10-1 char[1]")
NFA11_1("NFA11-1 char[1]")
NFA12_1[\"NFA12-1 char[1]
AcceptToken '+'"/]
class NFA12_1 c0001;
NFA13_1[\"NFA13-1 char[1]
AcceptToken '-'"/]
class NFA13_1 c0001;
NFA14_1[\"NFA14-1 char[1]
AcceptToken '!'"/]
class NFA14_1 c0001;
NFA15_1[\"NFA15-1 char[1]
AcceptToken '~'"/]
class NFA15_1 c0001;
NFA16_1[\"NFA16-1 char[1]
AcceptToken '*'"/]
class NFA16_1 c0001;
NFA17_1[\"NFA17-1 char[1]
AcceptToken '/'"/]
class NFA17_1 c0001;
NFA18_1[\"NFA18-1 char[1]
AcceptToken '%'"/]
class NFA18_1 c0001;
NFA19_1("NFA19-1 char[1]")
NFA20_1("NFA20-1 char[1]")
NFA21_1[\"NFA21-1 char[1]
AcceptToken '<'"/]
class NFA21_1 c0001;
NFA22_1[\"NFA22-1 char[1]
AcceptToken '>'"/]
class NFA22_1 c0001;
NFA23_1("NFA23-1 char[1]")
NFA24_1("NFA24-1 char[1]")
NFA25_1("NFA25-1 char[1]")
NFA26_1("NFA26-1 char[1]")
NFA27_1[\"NFA27-1 char[1]
AcceptToken '&'"/]
class NFA27_1 c0001;
NFA28_1[\"NFA28-1 char[1]
AcceptToken '^'"/]
class NFA28_1 c0001;
NFA29_1[\"NFA29-1 char[1]
AcceptToken '|'"/]
class NFA29_1 c0001;
NFA30_1("NFA30-1 char[1]")
NFA31_1("NFA31-1 char[1]")
NFA32_1("NFA32-1 char[1]")
NFA33_1[\"NFA33-1 char[1]
AcceptToken '?'"/]
class NFA33_1 c0001;
NFA34_1[\"NFA34-1 char[1]
AcceptToken ':'"/]
class NFA34_1 c0001;
NFA35_1[\"NFA35-1 char[1]
AcceptToken '='"/]
class NFA35_1 c0001;
NFA36_1("NFA36-1 char[1]")
NFA37_1("NFA37-1 char[1]")
NFA38_1("NFA38-1 char[1]")
NFA39_1("NFA39-1 char[1]")
NFA40_1("NFA40-1 char[1]")
NFA41_1("NFA41-1 char[1]")
NFA42_1("NFA42-1 char[1]")
NFA43_1("NFA43-1 char[1]")
NFA44_1("NFA44-1 char[1]")
NFA45_1("NFA45-1 char[1]")
NFA46_1[\"NFA46-1 char[1]
AcceptToken '{'"/]
class NFA46_1 c0001;
NFA47_1[\"NFA47-1 char[1]
AcceptToken '}'"/]
class NFA47_1 c0001;
NFA48_1("NFA48-1 char[1]")
NFA49_1("NFA49-1 char[1]")
NFA50_1("NFA50-1 char[1]")
NFA51_1("NFA51-1 char[1]")
NFA52_1("NFA52-1 char[1]")
NFA53_1("NFA53-1 char[1]")
NFA54_1("NFA54-1 char[1]")
NFA55_1("NFA55-1 char[1]")
NFA56_1("NFA56-1 char[1]")
NFA57_1("NFA57-1 char[1]")
NFA58_1("NFA58-1 char[1]")
NFA59_1("NFA59-1 char[1]")
NFA60_1("NFA60-1 char[1]")
NFA61_1[\"NFA61-1 scope[1]
AcceptToken 'identifier'"/]
class NFA61_1 c0001;
NFA62_1("NFA62-1 scope[1]")
class NFA62_1 c1000;
NFA63_1[\"NFA63-1 scope[1]
AcceptToken 'number'"/]
class NFA63_1 c0001;
NFA64_1("NFA64-1 scope[1]")
class NFA64_1 c1000;
NFA65_1("NFA65-1 char[1]")
NFA66_1("NFA66-1 scope[1]")
class NFA66_1 c1000;
NFA67_1("NFA67-1 char[1]")
NFA68_1("NFA68-1 scope[1]")
class NFA68_1 c1000;
NFA69_1("NFA69-1 char[1]")
NFA70_1("NFA70-1 char[1]")
NFA71_1("NFA71-1 scope[1]")
class NFA71_1 c1000;
NFA72_1("NFA72-1 char[1]")
NFA62_3("NFA62-3 char[1]")
NFA64_3[\"NFA64-3 scope[1]
AcceptToken 'intConstant'"/]
class NFA64_3 c0001;
NFA66_3("NFA66-3 scope[1]")
NFA68_3("NFA68-3 scope[1]")
NFA71_3[\"NFA71-3 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_3 c0001;
NFA1_3("NFA1-3 char[1]")
NFA4_3("NFA4-3 char[1]")
NFA10_3[\"NFA10-3 char[1]
AcceptToken '++'"/]
class NFA10_3 c0001;
NFA11_3[\"NFA11-3 char[1]
AcceptToken '--'"/]
class NFA11_3 c0001;
NFA19_3[\"NFA19-3 char[1]
AcceptToken '<<'"/]
class NFA19_3 c0001;
NFA20_3[\"NFA20-3 char[1]
AcceptToken '>>'"/]
class NFA20_3 c0001;
NFA23_3[\"NFA23-3 char[1]
AcceptToken '<='"/]
class NFA23_3 c0001;
NFA24_3[\"NFA24-3 char[1]
AcceptToken '>='"/]
class NFA24_3 c0001;
NFA25_3[\"NFA25-3 char[1]
AcceptToken '=='"/]
class NFA25_3 c0001;
NFA26_3[\"NFA26-3 char[1]
AcceptToken '!='"/]
class NFA26_3 c0001;
NFA30_3[\"NFA30-3 char[1]
AcceptToken '&&'"/]
class NFA30_3 c0001;
NFA31_3[\"NFA31-3 char[1]
AcceptToken '^^'"/]
class NFA31_3 c0001;
NFA32_3[\"NFA32-3 char[1]
AcceptToken '||'"/]
class NFA32_3 c0001;
NFA36_3[\"NFA36-3 char[1]
AcceptToken '*='"/]
class NFA36_3 c0001;
NFA37_3[\"NFA37-3 char[1]
AcceptToken '/='"/]
class NFA37_3 c0001;
NFA38_3[\"NFA38-3 char[1]
AcceptToken '%='"/]
class NFA38_3 c0001;
NFA39_3[\"NFA39-3 char[1]
AcceptToken '+='"/]
class NFA39_3 c0001;
NFA40_3[\"NFA40-3 char[1]
AcceptToken '-='"/]
class NFA40_3 c0001;
NFA41_3("NFA41-3 char[1]")
NFA42_3("NFA42-3 char[1]")
NFA43_3[\"NFA43-3 char[1]
AcceptToken '&='"/]
class NFA43_3 c0001;
NFA44_3[\"NFA44-3 char[1]
AcceptToken '^='"/]
class NFA44_3 c0001;
NFA45_3[\"NFA45-3 char[1]
AcceptToken '|='"/]
class NFA45_3 c0001;
NFA48_3[\"NFA48-3 char[1]
AcceptToken '##'"/]
class NFA48_3 c0001;
NFA49_3("NFA49-3 char[1]")
NFA50_3("NFA50-3 char[1]")
NFA51_3("NFA51-3 char[1]")
NFA52_3("NFA52-3 char[1]")
NFA53_3("NFA53-3 char[1]")
NFA54_3("NFA54-3 char[1]")
NFA55_3("NFA55-3 char[1]")
NFA56_3("NFA56-3 char[1]")
NFA57_3("NFA57-3 char[1]")
NFA58_3("NFA58-3 char[1]")
NFA59_3("NFA59-3 char[1]")
NFA60_3("NFA60-3 char[1]")
NFA61_2[\"NFA61-2 scope{0, -1}
AcceptToken 'identifier'"/]
class NFA61_2 c0001;
NFA63_3("NFA63-3 scope[1]")
NFA65_3("NFA65-3 char[1]")
NFA67_3("NFA67-3 char[1]")
NFA69_3("NFA69-3 char[1]")
NFA70_3("NFA70-3 char[1]")
NFA72_3[\"NFA72-3 char[1]
AcceptToken 'inlineComment'"/]
class NFA72_3 c0001;
NFA62_5("NFA62-5 char[1]")
NFA62_11("NFA62-11 scope[1]")
NFA62_13[\"NFA62-13 char[1]
AcceptToken 'literalString'"/]
class NFA62_13 c0001;
NFA66_5[\"NFA66-5 scope[1]
AcceptToken 'uintConstant'"/]
class NFA66_5 c0001;
NFA68_5("NFA68-5 scope[1]")
NFA68_10("NFA68-10 scope[1]")
NFA68_18[\"NFA68-18 scope[1]
AcceptToken 'floatConstant'"/]
class NFA68_18 c0001;
NFA71_5[\"NFA71-5 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_5 c0001;
NFA71_10("NFA71-10 scope[1]")
NFA1_5("NFA1-5 char[1]")
NFA4_5("NFA4-5 char[1]")
NFA41_5[\"NFA41-5 char[1]
AcceptToken '<<='"/]
class NFA41_5 c0001;
NFA42_5[\"NFA42-5 char[1]
AcceptToken '>>='"/]
class NFA42_5 c0001;
NFA49_5[\"NFA49-5 char[1]
AcceptToken '#if'"/]
class NFA49_5 c0001;
NFA50_5("NFA50-5 char[1]")
NFA51_5("NFA51-5 char[1]")
NFA52_5("NFA52-5 char[1]")
NFA53_5("NFA53-5 char[1]")
NFA54_5("NFA54-5 char[1]")
NFA55_5("NFA55-5 char[1]")
NFA56_5("NFA56-5 char[1]")
NFA57_5("NFA57-5 char[1]")
NFA58_5("NFA58-5 char[1]")
NFA59_5("NFA59-5 char[1]")
NFA60_5("NFA60-5 char[1]")
NFA63_5[\"NFA63-5 scope[1]
AcceptToken 'number'"/]
class NFA63_5 c0001;
NFA65_5[\"NFA65-5 scope[1]
AcceptToken 'intConstant'"/]
class NFA65_5 c0001;
NFA67_5("NFA67-5 scope[1]")
NFA69_5("NFA69-5 char[1]")
NFA70_5("NFA70-5 char[1]")
NFA72_4[\"NFA72-4 scope{0, -1}
AcceptToken 'inlineComment'"/]
class NFA72_4 c0001;
NFA62_7("NFA62-7 char[1]")
NFA68_6("NFA68-6 scope{0, -1}")
NFA68_5("NFA68-5 scope[1]")
NFA68_12("NFA68-12 scope[1]")
NFA68_14("NFA68-14 scope[1]")
NFA71_6[\"NFA71-6 scope{0, -1}
AcceptToken 'doubleConstant'"/]
class NFA71_6 c0001;
NFA71_5[\"NFA71-5 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_5 c0001;
NFA71_12("NFA71-12 scope[1]")
NFA71_14[\"NFA71-14 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_14 c0001;
NFA1_7("NFA1-7 char[1]")
NFA4_7("NFA4-7 char[1]")
NFA50_7("NFA50-7 char[1]")
NFA51_7("NFA51-7 char[1]")
NFA52_7("NFA52-7 char[1]")
NFA53_7("NFA53-7 char[1]")
NFA54_7("NFA54-7 char[1]")
NFA55_7("NFA55-7 char[1]")
NFA56_7("NFA56-7 char[1]")
NFA57_7("NFA57-7 char[1]")
NFA58_7("NFA58-7 char[1]")
NFA59_7("NFA59-7 char[1]")
NFA60_7("NFA60-7 char[1]")
NFA63_3("NFA63-3 scope[1]")
NFA67_7[\"NFA67-7 scope[1]
AcceptToken 'uintConstant'"/]
class NFA67_7 c0001;
NFA69_7("NFA69-7 char[1]")
NFA70_7("NFA70-7 char[1]")
NFA68_6("NFA68-6 scope{0, -1}")
NFA68_10("NFA68-10 scope[1]")
NFA71_6[\"NFA71-6 scope{0, -1}
AcceptToken 'doubleConstant'"/]
class NFA71_6 c0001;
NFA71_10("NFA71-10 scope[1]")
NFA1_9("NFA1-9 char[1]")
NFA4_9("NFA4-9 char[1]")
NFA50_9("NFA50-9 char[1]")
NFA51_9("NFA51-9 char[1]")
NFA52_9[\"NFA52-9 char[1]
AcceptToken '#else'"/]
class NFA52_9 c0001;
NFA53_9[\"NFA53-9 char[1]
AcceptToken '#elif'"/]
class NFA53_9 c0001;
NFA54_9("NFA54-9 char[1]")
NFA55_9("NFA55-9 char[1]")
NFA56_9("NFA56-9 char[1]")
NFA57_9("NFA57-9 char[1]")
NFA58_9("NFA58-9 char[1]")
NFA59_9[\"NFA59-9 char[1]
AcceptToken '#line'"/]
class NFA59_9 c0001;
NFA60_9("NFA60-9 char[1]")
NFA63_5[\"NFA63-5 scope[1]
AcceptToken 'number'"/]
class NFA63_5 c0001;
NFA69_11[\"NFA69-11 scope[1]
AcceptToken 'boolConstant'"/]
class NFA69_11 c0001;
NFA70_9("NFA70-9 char[1]")
NFA68_12("NFA68-12 scope[1]")
NFA68_14("NFA68-14 scope[1]")
NFA71_12("NFA71-12 scope[1]")
NFA71_14[\"NFA71-14 scope[1]
AcceptToken 'doubleConstant'"/]
class NFA71_14 c0001;
NFA1_11("NFA1-11 char[1]")
NFA4_11[\"NFA4-11 char[1]
AcceptToken '#undef'"/]
class NFA4_11 c0001;
NFA50_11[\"NFA50-11 char[1]
AcceptToken '#ifdef'"/]
class NFA50_11 c0001;
NFA51_11("NFA51-11 char[1]")
NFA54_11[\"NFA54-11 char[1]
AcceptToken '#endif'"/]
class NFA54_11 c0001;
NFA55_11[\"NFA55-11 char[1]
AcceptToken '#error'"/]
class NFA55_11 c0001;
NFA56_11("NFA56-11 char[1]")
NFA57_11("NFA57-11 char[1]")
NFA58_11("NFA58-11 char[1]")
NFA60_11("NFA60-11 char[1]")
NFA70_13[\"NFA70-13 scope[1]
AcceptToken 'boolConstant'"/]
class NFA70_13 c0001;
NFA1_13[\"NFA1-13 char[1]
AcceptToken '#define'"/]
class NFA1_13 c0001;
NFA51_13[\"NFA51-13 char[1]
AcceptToken '#ifndef'"/]
class NFA51_13 c0001;
NFA56_13[\"NFA56-13 char[1]
AcceptToken '#pragma'"/]
class NFA56_13 c0001;
NFA57_13("NFA57-13 char[1]")
NFA58_13("NFA58-13 char[1]")
NFA60_13[\"NFA60-13 char[1]
AcceptToken 'defined'"/]
class NFA60_13 c0001;
NFA57_15("NFA57-15 char[1]")
NFA58_15[\"NFA58-15 char[1]
AcceptToken '#version'"/]
class NFA58_15 c0001;
NFA57_17("NFA57-17 char[1]")
NFA57_19[\"NFA57-19 char[1]
AcceptToken '#extension'"/]
class NFA57_19 c0001;
NFA0_0 -->|"#35;
BeginToken '#35;define'"|NFA1_1
NFA0_0 -->|"#92;(
BeginToken '('
ExtendToken '('"|NFA2_1
NFA0_0 -->|"#92;)
BeginToken ')'
ExtendToken ')'"|NFA3_1
NFA0_0 -->|"#35;
BeginToken '#35;undef'"|NFA4_1
NFA0_0 -->|",
BeginToken ','
ExtendToken ','"|NFA5_1
NFA0_0 -->|";
BeginToken ';'
ExtendToken ';'"|NFA6_1
NFA0_0 -->|"#92;[
BeginToken '['
ExtendToken '['"|NFA7_1
NFA0_0 -->|"]
BeginToken ']'
ExtendToken ']'"|NFA8_1
NFA0_0 -->|"#92;.
BeginToken '.'
ExtendToken '.'"|NFA9_1
NFA0_0 -->|"#92;+
BeginToken '++'"|NFA10_1
NFA0_0 -->|"-
BeginToken '--'"|NFA11_1
NFA0_0 -->|"#92;+
BeginToken '+'
ExtendToken '+'"|NFA12_1
NFA0_0 -->|"-
BeginToken '-'
ExtendToken '-'"|NFA13_1
NFA0_0 -->|"!
BeginToken '!'
ExtendToken '!'"|NFA14_1
NFA0_0 -->|"~
BeginToken '~'
ExtendToken '~'"|NFA15_1
NFA0_0 -->|"#92;#42;
BeginToken '#42;'
ExtendToken '#42;'"|NFA16_1
NFA0_0 -->|"#92;/
BeginToken '/'
ExtendToken '/'"|NFA17_1
NFA0_0 -->|"%
BeginToken '%'
ExtendToken '%'"|NFA18_1
NFA0_0 -->|"#92;<
BeginToken '<<'"|NFA19_1
NFA0_0 -->|">
BeginToken '>>'"|NFA20_1
NFA0_0 -->|"#92;<
BeginToken '<'
ExtendToken '<'"|NFA21_1
NFA0_0 -->|">
BeginToken '>'
ExtendToken '>'"|NFA22_1
NFA0_0 -->|"#92;<
BeginToken '<='"|NFA23_1
NFA0_0 -->|">
BeginToken '>='"|NFA24_1
NFA0_0 -->|"=
BeginToken '=='"|NFA25_1
NFA0_0 -->|"!
BeginToken '!='"|NFA26_1
NFA0_0 -->|"&
BeginToken '&'
ExtendToken '&'"|NFA27_1
NFA0_0 -->|"^
BeginToken '^'
ExtendToken '^'"|NFA28_1
NFA0_0 -->|"#92;|
BeginToken '|'
ExtendToken '|'"|NFA29_1
NFA0_0 -->|"&
BeginToken '&&'"|NFA30_1
NFA0_0 -->|"^
BeginToken '^^'"|NFA31_1
NFA0_0 -->|"#92;|
BeginToken '||'"|NFA32_1
NFA0_0 -->|"#92;?
BeginToken '?'
ExtendToken '?'"|NFA33_1
NFA0_0 -->|":
BeginToken ':'
ExtendToken ':'"|NFA34_1
NFA0_0 -->|"=
BeginToken '='
ExtendToken '='"|NFA35_1
NFA0_0 -->|"#92;#42;
BeginToken '#42;='"|NFA36_1
NFA0_0 -->|"#92;/
BeginToken '/='"|NFA37_1
NFA0_0 -->|"%
BeginToken '%='"|NFA38_1
NFA0_0 -->|"#92;+
BeginToken '+='"|NFA39_1
NFA0_0 -->|"-
BeginToken '-='"|NFA40_1
NFA0_0 -->|"#92;<
BeginToken '<<='"|NFA41_1
NFA0_0 -->|">
BeginToken '>>='"|NFA42_1
NFA0_0 -->|"&
BeginToken '&='"|NFA43_1
NFA0_0 -->|"^
BeginToken '^='"|NFA44_1
NFA0_0 -->|"#92;|
BeginToken '|='"|NFA45_1
NFA0_0 -->|"#92;{
BeginToken '{'
ExtendToken '{'"|NFA46_1
NFA0_0 -->|"}
BeginToken '}'
ExtendToken '}'"|NFA47_1
NFA0_0 -->|"#35;
BeginToken '#35;#35;'"|NFA48_1
NFA0_0 -->|"#35;
BeginToken '#35;if'"|NFA49_1
NFA0_0 -->|"#35;
BeginToken '#35;ifdef'"|NFA50_1
NFA0_0 -->|"#35;
BeginToken '#35;ifndef'"|NFA51_1
NFA0_0 -->|"#35;
BeginToken '#35;else'"|NFA52_1
NFA0_0 -->|"#35;
BeginToken '#35;elif'"|NFA53_1
NFA0_0 -->|"#35;
BeginToken '#35;endif'"|NFA54_1
NFA0_0 -->|"#35;
BeginToken '#35;error'"|NFA55_1
NFA0_0 -->|"#35;
BeginToken '#35;pragma'"|NFA56_1
NFA0_0 -->|"#35;
BeginToken '#35;extension'"|NFA57_1
NFA0_0 -->|"#35;
BeginToken '#35;version'"|NFA58_1
NFA0_0 -->|"#35;
BeginToken '#35;line'"|NFA59_1
NFA0_0 -->|"d
BeginToken 'defined'"|NFA60_1
NFA0_0 -->|"[a-zA-Z_]
BeginToken 'identifier'
ExtendToken 'identifier'"|NFA61_1
NFA0_0 -->|"[a-zA-Z_]
BeginToken 'literalString'"|NFA62_1
NFA0_0 -->|"[0-9]
BeginToken 'number'
ExtendToken 'number'"|NFA63_1
NFA0_0 -->|"[-+]
BeginToken 'intConstant'"|NFA64_1
NFA0_0 -->|"0
BeginToken 'intConstant'"|NFA65_1
NFA0_0 -->|"[-+]
BeginToken 'uintConstant'"|NFA66_1
NFA0_0 -->|"0
BeginToken 'uintConstant'"|NFA67_1
NFA0_0 -->|"[-+]
BeginToken 'floatConstant'"|NFA68_1
NFA0_0 -->|"t
BeginToken 'boolConstant'"|NFA69_1
NFA0_0 -->|"f
BeginToken 'boolConstant'"|NFA70_1
NFA0_0 -->|"[-+]
BeginToken 'doubleConstant'"|NFA71_1
NFA0_0 -->|"#92;/
BeginToken 'inlineComment'"|NFA72_1
NFA0_0 -->|"#34;
BeginToken 'literalString'"|NFA62_3
NFA0_0 -->|"[0-9]
BeginToken 'intConstant'
ExtendToken 'intConstant'"|NFA64_3
NFA0_0 -->|"[0-9]
BeginToken 'uintConstant'"|NFA66_3
NFA0_0 -->|"[0-9]
BeginToken 'floatConstant'"|NFA68_3
NFA0_0 -->|"[0-9]
BeginToken 'doubleConstant'
ExtendToken 'doubleConstant'"|NFA71_3
NFA1_1 -->|"d"|NFA1_3
NFA4_1 -->|"u"|NFA4_3
NFA10_1 -->|"#92;+
ExtendToken '++'"|NFA10_3
NFA11_1 -->|"-
ExtendToken '--'"|NFA11_3
NFA19_1 -->|"#92;<
ExtendToken '<<'"|NFA19_3
NFA20_1 -->|">
ExtendToken '>>'"|NFA20_3
NFA23_1 -->|"=
ExtendToken '<='"|NFA23_3
NFA24_1 -->|"=
ExtendToken '>='"|NFA24_3
NFA25_1 -->|"=
ExtendToken '=='"|NFA25_3
NFA26_1 -->|"=
ExtendToken '!='"|NFA26_3
NFA30_1 -->|"&
ExtendToken '&&'"|NFA30_3
NFA31_1 -->|"^
ExtendToken '^^'"|NFA31_3
NFA32_1 -->|"#92;|
ExtendToken '||'"|NFA32_3
NFA36_1 -->|"=
ExtendToken '#42;='"|NFA36_3
NFA37_1 -->|"=
ExtendToken '/='"|NFA37_3
NFA38_1 -->|"=
ExtendToken '%='"|NFA38_3
NFA39_1 -->|"=
ExtendToken '+='"|NFA39_3
NFA40_1 -->|"=
ExtendToken '-='"|NFA40_3
NFA41_1 -->|"#92;<"|NFA41_3
NFA42_1 -->|">"|NFA42_3
NFA43_1 -->|"=
ExtendToken '&='"|NFA43_3
NFA44_1 -->|"=
ExtendToken '^='"|NFA44_3
NFA45_1 -->|"=
ExtendToken '|='"|NFA45_3
NFA48_1 -->|"#35;
ExtendToken '#35;#35;'"|NFA48_3
NFA49_1 -->|"i"|NFA49_3
NFA50_1 -->|"i"|NFA50_3
NFA51_1 -->|"i"|NFA51_3
NFA52_1 -->|"e"|NFA52_3
NFA53_1 -->|"e"|NFA53_3
NFA54_1 -->|"e"|NFA54_3
NFA55_1 -->|"e"|NFA55_3
NFA56_1 -->|"p"|NFA56_3
NFA57_1 -->|"e"|NFA57_3
NFA58_1 -->|"v"|NFA58_3
NFA59_1 -->|"l"|NFA59_3
NFA60_1 -->|"e"|NFA60_3
NFA61_1 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier'"|NFA61_2
NFA62_1 -->|"#34;
BeginToken 'literalString'"|NFA62_3
NFA63_1 -->|"[0-9]
ExtendToken 'number'"|NFA63_1
NFA63_1 -->|"[.]"|NFA63_3
NFA64_1 -->|"[0-9]
BeginToken 'intConstant'
ExtendToken 'intConstant'"|NFA64_3
NFA65_1 -->|"x"|NFA65_3
NFA66_1 -->|"[0-9]
BeginToken 'uintConstant'"|NFA66_3
NFA67_1 -->|"x"|NFA67_3
NFA68_1 -->|"[0-9]
BeginToken 'floatConstant'"|NFA68_3
NFA69_1 -->|"r"|NFA69_3
NFA70_1 -->|"a"|NFA70_3
NFA71_1 -->|"[0-9]
BeginToken 'doubleConstant'
ExtendToken 'doubleConstant'"|NFA71_3
NFA72_1 -->|"#92;/
ExtendToken 'inlineComment'"|NFA72_3
NFA62_3 -->|"#92;#92;"|NFA62_5
NFA62_3 -->|"[^#92;#92;#34;]"|NFA62_11
NFA62_3 -->|"#34;
ExtendToken 'literalString'"|NFA62_13
NFA64_3 -->|"[0-9]
ExtendToken 'intConstant'"|NFA64_3
NFA66_3 -->|"[0-9]"|NFA66_3
NFA66_3 -->|"[uU]
ExtendToken 'uintConstant'"|NFA66_5
NFA68_3 -->|"[0-9]"|NFA68_3
NFA68_3 -->|"[.]"|NFA68_5
NFA68_3 -->|"[Ee]"|NFA68_10
NFA68_3 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA71_3 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_3
NFA71_3 -->|"[.]
ExtendToken 'doubleConstant'"|NFA71_5
NFA71_3 -->|"[Ee]"|NFA71_10
NFA1_3 -->|"e"|NFA1_5
NFA4_3 -->|"n"|NFA4_5
NFA41_3 -->|"=
ExtendToken '<<='"|NFA41_5
NFA42_3 -->|"=
ExtendToken '>>='"|NFA42_5
NFA49_3 -->|"f
ExtendToken '#35;if'"|NFA49_5
NFA50_3 -->|"f"|NFA50_5
NFA51_3 -->|"f"|NFA51_5
NFA52_3 -->|"l"|NFA52_5
NFA53_3 -->|"l"|NFA53_5
NFA54_3 -->|"n"|NFA54_5
NFA55_3 -->|"r"|NFA55_5
NFA56_3 -->|"r"|NFA56_5
NFA57_3 -->|"x"|NFA57_5
NFA58_3 -->|"e"|NFA58_5
NFA59_3 -->|"i"|NFA59_5
NFA60_3 -->|"f"|NFA60_5
NFA61_2 -->|"[a-zA-Z0-9_]
ExtendToken 'identifier'"|NFA61_2
NFA63_3 -->|"[0-9]
ExtendToken 'number'"|NFA63_5
NFA65_3 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant'"|NFA65_5
NFA67_3 -->|"[0-9A-Fa-f]"|NFA67_5
NFA69_3 -->|"u"|NFA69_5
NFA70_3 -->|"l"|NFA70_5
NFA72_3 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment'"|NFA72_4
NFA62_5 -->|"[#32;-~]"|NFA62_7
NFA62_11 -->|"#92;#92;"|NFA62_5
NFA62_11 -->|"[^#92;#92;#34;]"|NFA62_11
NFA62_11 -->|"#34;
ExtendToken 'literalString'"|NFA62_13
NFA68_5 -->|"[0-9]"|NFA68_6
NFA68_5 -->|"[.]"|NFA68_5
NFA68_5 -->|"[Ee]"|NFA68_10
NFA68_5 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA68_10 -->|"[-+]"|NFA68_12
NFA68_10 -->|"[0-9]"|NFA68_14
NFA71_5 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_6
NFA71_5 -->|"[.]
ExtendToken 'doubleConstant'"|NFA71_5
NFA71_5 -->|"[Ee]"|NFA71_10
NFA71_10 -->|"[-+]"|NFA71_12
NFA71_10 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_14
NFA1_5 -->|"f"|NFA1_7
NFA4_5 -->|"d"|NFA4_7
NFA50_5 -->|"d"|NFA50_7
NFA51_5 -->|"n"|NFA51_7
NFA52_5 -->|"s"|NFA52_7
NFA53_5 -->|"i"|NFA53_7
NFA54_5 -->|"d"|NFA54_7
NFA55_5 -->|"r"|NFA55_7
NFA56_5 -->|"a"|NFA56_7
NFA57_5 -->|"t"|NFA57_7
NFA58_5 -->|"r"|NFA58_7
NFA59_5 -->|"n"|NFA59_7
NFA60_5 -->|"i"|NFA60_7
NFA63_5 -->|"[0-9]
ExtendToken 'number'"|NFA63_5
NFA63_5 -->|"[.]"|NFA63_3
NFA65_5 -->|"[0-9A-Fa-f]
ExtendToken 'intConstant'"|NFA65_5
NFA67_5 -->|"[0-9A-Fa-f]"|NFA67_5
NFA67_5 -->|"[uU]
ExtendToken 'uintConstant'"|NFA67_7
NFA69_5 -->|"e
ExtendToken 'boolConstant'"|NFA69_7
NFA70_5 -->|"s"|NFA70_7
NFA72_4 -->|"[^#92;n#92;r#92;u0000]
ExtendToken 'inlineComment'"|NFA72_4
NFA62_7 -->|"#92;#92;"|NFA62_5
NFA62_7 -->|"[^#92;#92;#34;]"|NFA62_11
NFA62_7 -->|"#34;
ExtendToken 'literalString'"|NFA62_13
NFA68_6 -->|"[0-9]"|NFA68_6
NFA68_6 -->|"[.]"|NFA68_5
NFA68_6 -->|"[Ee]"|NFA68_10
NFA68_6 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA68_5 -->|"[0-9]"|NFA68_6
NFA68_5 -->|"[Ee]"|NFA68_10
NFA68_5 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA68_12 -->|"[0-9]"|NFA68_14
NFA68_14 -->|"[0-9]"|NFA68_14
NFA68_14 -->|"[Ee]"|NFA68_10
NFA68_14 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA71_6 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_6
NFA71_6 -->|"[.]
ExtendToken 'doubleConstant'"|NFA71_5
NFA71_6 -->|"[Ee]"|NFA71_10
NFA71_5 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_6
NFA71_5 -->|"[Ee]"|NFA71_10
NFA71_12 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_14
NFA71_14 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_14
NFA71_14 -->|"[Ee]"|NFA71_10
NFA1_7 -->|"i"|NFA1_9
NFA4_7 -->|"e"|NFA4_9
NFA50_7 -->|"e"|NFA50_9
NFA51_7 -->|"d"|NFA51_9
NFA52_7 -->|"e
ExtendToken '#35;else'"|NFA52_9
NFA53_7 -->|"f
ExtendToken '#35;elif'"|NFA53_9
NFA54_7 -->|"i"|NFA54_9
NFA55_7 -->|"o"|NFA55_9
NFA56_7 -->|"g"|NFA56_9
NFA57_7 -->|"e"|NFA57_9
NFA58_7 -->|"s"|NFA58_9
NFA59_7 -->|"e
ExtendToken '#35;line'"|NFA59_9
NFA60_7 -->|"n"|NFA60_9
NFA63_3 -->|"[0-9]
ExtendToken 'number'"|NFA63_5
NFA69_7 -->|"[^a-zA-Z0-9_]"|NFA69_11
NFA70_7 -->|"e
ExtendToken 'boolConstant'"|NFA70_9
NFA68_6 -->|"[0-9]"|NFA68_6
NFA68_6 -->|"[Ee]"|NFA68_10
NFA68_6 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA68_10 -->|"[-+]"|NFA68_12
NFA68_10 -->|"[0-9]"|NFA68_14
NFA71_6 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_6
NFA71_6 -->|"[Ee]"|NFA71_10
NFA71_10 -->|"[-+]"|NFA71_12
NFA71_10 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_14
NFA1_9 -->|"n"|NFA1_11
NFA4_9 -->|"f
ExtendToken '#35;undef'"|NFA4_11
NFA50_9 -->|"f
ExtendToken '#35;ifdef'"|NFA50_11
NFA51_9 -->|"e"|NFA51_11
NFA54_9 -->|"f
ExtendToken '#35;endif'"|NFA54_11
NFA55_9 -->|"r
ExtendToken '#35;error'"|NFA55_11
NFA56_9 -->|"m"|NFA56_11
NFA57_9 -->|"n"|NFA57_11
NFA58_9 -->|"i"|NFA58_11
NFA60_9 -->|"e"|NFA60_11
NFA63_5 -->|"[0-9]
ExtendToken 'number'"|NFA63_5
NFA70_9 -->|"[^a-zA-Z0-9_]"|NFA70_13
NFA68_12 -->|"[0-9]"|NFA68_14
NFA68_14 -->|"[0-9]"|NFA68_14
NFA68_14 -->|"[fF]
ExtendToken 'floatConstant'"|NFA68_18
NFA71_12 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_14
NFA71_14 -->|"[0-9]
ExtendToken 'doubleConstant'"|NFA71_14
NFA1_11 -->|"e
ExtendToken '#35;define'"|NFA1_13
NFA51_11 -->|"f
ExtendToken '#35;ifndef'"|NFA51_13
NFA56_11 -->|"a
ExtendToken '#35;pragma'"|NFA56_13
NFA57_11 -->|"s"|NFA57_13
NFA58_11 -->|"o"|NFA58_13
NFA60_11 -->|"d
ExtendToken 'defined'"|NFA60_13
NFA57_13 -->|"i"|NFA57_15
NFA58_13 -->|"n
ExtendToken '#35;version'"|NFA58_15
NFA57_15 -->|"o"|NFA57_17
NFA57_17 -->|"n
ExtendToken '#35;extension'"|NFA57_19
